In [2]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('emissions.csv')

# Print the DataFrame
print(df)

       year state-name                                      sector-name  \
0      1970    Alabama              Industrial carbon dioxide emissions
1      1970    Alabama              Industrial carbon dioxide emissions
2      1970    Alabama              Industrial carbon dioxide emissions
3      1970    Alabama              Industrial carbon dioxide emissions
4      1970    Alabama  Total carbon dioxide emissions from all sectors
...     ...        ...                                              ...
59896  2021    Wyoming              Commercial carbon dioxide emissions
59897  2021    Wyoming             Residential carbon dioxide emissions
59898  2021    Wyoming             Residential carbon dioxide emissions
59899  2021    Wyoming             Residential carbon dioxide emissions
59900  2021    Wyoming  Total carbon dioxide emissions from all sectors

         fuel-name       value
0             Coal   26.721507
1        Petroleum    3.577779
2      Natural Gas    8.944097
3        All Fuels   39.243383
4        All Fuels  102.646851
...            ...         ...
59896         Coal    0.012374
59897    All Fuels    0.937989
59898  Natural Gas    0.717777
59899    Petroleum    0.220212
59900    Petroleum   10.198574

[59901 rows x 5 columns]

In [5]:
# Drop rows that contain "all" in any cell
df = df[~df.apply(lambda row: row.astype(str).str.contains('all').any(), axis=1)]

# Print the DataFrame after dropping rows
print(df)

       year state-name                           sector-name    fuel-name  \
0      1970    Alabama   Industrial carbon dioxide emissions         Coal
1      1970    Alabama   Industrial carbon dioxide emissions    Petroleum
2      1970    Alabama   Industrial carbon dioxide emissions  Natural Gas
3      1970    Alabama   Industrial carbon dioxide emissions    All Fuels
8      1970    Alabama  Residential carbon dioxide emissions         Coal
...     ...        ...                                   ...          ...
59895  2021    Wyoming   Commercial carbon dioxide emissions    Petroleum
59896  2021    Wyoming   Commercial carbon dioxide emissions         Coal
59897  2021    Wyoming  Residential carbon dioxide emissions    All Fuels
59898  2021    Wyoming  Residential carbon dioxide emissions  Natural Gas
59899  2021    Wyoming  Residential carbon dioxide emissions    Petroleum

           value
0      26.721507
1       3.577779
2       8.944097
3      39.243383
8       0.163635
...          ...
59895   0.216315
59896   0.012374
59897   0.937989
59898   0.717777
59899   0.220212

[49148 rows x 5 columns]

In [6]:
# Drop rows that contain "all" in any cell
df = df[~df.apply(lambda row: row.astype(str).str.contains('All').any(), axis=1)]

# Print the DataFrame after dropping rows
print(df)

       year state-name                           sector-name    fuel-name  \
0      1970    Alabama   Industrial carbon dioxide emissions         Coal
1      1970    Alabama   Industrial carbon dioxide emissions    Petroleum
2      1970    Alabama   Industrial carbon dioxide emissions  Natural Gas
8      1970    Alabama  Residential carbon dioxide emissions         Coal
9      1970    Alabama  Residential carbon dioxide emissions    Petroleum
...     ...        ...                                   ...          ...
59894  2021    Wyoming   Commercial carbon dioxide emissions  Natural Gas
59895  2021    Wyoming   Commercial carbon dioxide emissions    Petroleum
59896  2021    Wyoming   Commercial carbon dioxide emissions         Coal
59898  2021    Wyoming  Residential carbon dioxide emissions  Natural Gas
59899  2021    Wyoming  Residential carbon dioxide emissions    Petroleum

           value
0      26.721507
1       3.577779
2       8.944097
8       0.163635
9       1.123947
...          ...
59894   0.686983
59895   0.216315
59896   0.012374
59898   0.717777
59899   0.220212

[35638 rows x 5 columns]

In [ ]:
# Write the DataFrame to a CSV file
df.to_csv('emissionsMinAll.csv', index=False)

In [7]:
# Group by 'year', 'sector-name', and 'fuel-name' and sum the 'value' column
aggregated_df = df.groupby(['year', 'sector-name', 'fuel-name'])['value'].sum().reset_index()

# Print the aggregated DataFrame
print(aggregated_df)

     year                              sector-name    fuel-name        value
0    1970      Commercial carbon dioxide emissions         Coal    31.306261
1    1970      Commercial carbon dioxide emissions  Natural Gas   260.289232
2    1970      Commercial carbon dioxide emissions    Petroleum   233.356940
3    1970  Electric Power carbon dioxide emissions         Coal  1374.959395
4    1970  Electric Power carbon dioxide emissions  Natural Gas   429.208459
..    ...                                      ...          ...          ...
717  2021      Industrial carbon dioxide emissions    Petroleum   698.180684
718  2021     Residential carbon dioxide emissions  Natural Gas   520.017628
719  2021     Residential carbon dioxide emissions    Petroleum   132.467958
720  2021  Transportation carbon dioxide emissions  Natural Gas   129.829709
721  2021  Transportation carbon dioxide emissions    Petroleum  3499.876283

[722 rows x 4 columns]

In [8]:
# Write the DataFrame to a CSV file
aggregated_df.to_csv('emissionsMinAllAggregated.csv', index=False)

In [11]:
# Find the maximum value (year) in the 'year' column
max_year = aggregated_df['year'].max()

# Print the max year
print("Max year:", max_year)

Max year: 2021

In [12]:
# Find the minimum value (year) in the 'year' column
min_year = aggregated_df['year'].min()

# Print the min year
print("Min year:", min_year)

Min year: 1970

In [13]:
# Count the number of rows per year
rows_per_year = aggregated_df['year'].value_counts()

# Print the result
print("Rows per year:")
print(rows_per_year)

Rows per year:
1970    15
1972    15
1973    15
1974    15
1975    15
1976    15
1977    15
1971    15
2001    14
1995    14
1997    14
1998    14
1999    14
2000    14
2004    14
2002    14
2003    14
1993    14
2005    14
2006    14
2007    14
1994    14
1996    14
1992    14
1984    14
1991    14
1979    14
1980    14
1981    14
1982    14
1983    14
1978    14
1985    14
1987    14
1988    14
1989    14
1990    14
1986    14
2015    13
2020    13
2019    13
2018    13
2017    13
2016    13
2012    13
2014    13
2013    13
2011    13
2010    13
2009    13
2008    13
2021    13
Name: year, dtype: int64

In [16]:
# Get all unique values in the 'sector-name' column
unique_sectors = aggregated_df['sector-name'].unique()

# Print the unique values
print("Unique values in the 'sector-name' column:")
for sector in unique_sectors:
    print(sector)

Unique values in the 'sector-name' column:
Commercial carbon dioxide emissions
Electric Power carbon dioxide emissions
Industrial carbon dioxide emissions
Residential carbon dioxide emissions
Transportation carbon dioxide emissions

In [17]:
# Get all unique values in the 'fuel-name' column
unique_fuels = aggregated_df['fuel-name'].unique()

# Print the unique values
print("Unique values in the 'fuel-name' column:")
for fuel in unique_fuels:
    print(fuel)

Unique values in the 'fuel-name' column:
Coal
Natural Gas
Petroleum

In [19]:
# Create a pivot table with 'year', 'sector-name', and 'fuel-name' as indices and 'value' as values
pivot_df = aggregated_df.pivot_table(index=['year', 'sector-name', 'fuel-name'], values='value', aggfunc='sum').reset_index()

# Create a MultiIndex with all possible combinations of 'year', 'sector-name', and 'fuel-name'
all_years = aggregated_df['year'].unique()
all_sectors = aggregated_df['sector-name'].unique()
all_fuels = aggregated_df['fuel-name'].unique()
index = pd.MultiIndex.from_product([all_years, all_sectors, all_fuels], names=['year', 'sector-name', 'fuel-name'])

# Reindex the pivot table with the MultiIndex and fill missing values with 0
pivot_df = pivot_df.set_index(['year', 'sector-name', 'fuel-name']).reindex(index, fill_value=0).reset_index()

# Print the resulting DataFrame
print(pivot_df)

     year                              sector-name    fuel-name        value
0    1970      Commercial carbon dioxide emissions         Coal    31.306261
1    1970      Commercial carbon dioxide emissions  Natural Gas   260.289232
2    1970      Commercial carbon dioxide emissions    Petroleum   233.356940
3    1970  Electric Power carbon dioxide emissions         Coal  1374.959395
4    1970  Electric Power carbon dioxide emissions  Natural Gas   429.208459
..    ...                                      ...          ...          ...
775  2021     Residential carbon dioxide emissions  Natural Gas   520.017628
776  2021     Residential carbon dioxide emissions    Petroleum   132.467958
777  2021  Transportation carbon dioxide emissions         Coal     0.000000
778  2021  Transportation carbon dioxide emissions  Natural Gas   129.829709
779  2021  Transportation carbon dioxide emissions    Petroleum  3499.876283

[780 rows x 4 columns]

In [20]:
# Write the DataFrame to a CSV file
pivot_df.to_csv('emissionsMinAllAggregatedPivot.csv', index=False)

In [21]:
# Count the number of rows per year
rows_per_year = pivot_df['year'].value_counts()

# Print the result
print("Rows per year:")
print(rows_per_year)

Rows per year:
1970    15
1971    15
1998    15
1999    15
2000    15
2001    15
2002    15
2003    15
2004    15
2005    15
2006    15
2007    15
2008    15
2009    15
2010    15
2011    15
2012    15
2013    15
2014    15
2015    15
2016    15
2017    15
2018    15
2019    15
2020    15
1997    15
1996    15
1995    15
1982    15
1972    15
1973    15
1974    15
1975    15
1976    15
1977    15
1978    15
1979    15
1980    15
1981    15
1983    15
1994    15
1984    15
1985    15
1986    15
1987    15
1988    15
1989    15
1990    15
1991    15
1992    15
1993    15
2021    15
Name: year, dtype: int64

In [22]:
# Sort the DataFrame by the 'year' column
pivot_df_sorted = pivot_df.sort_values(by='year')

In [88]:
# Group the DataFrame by 'sector-name'
grouped = pivot_df_sorted.groupby(['sector-name'])

# Create a dictionary to store the DataFrames
dfs_sector_name = {}

# Iterate over each group and store the corresponding DataFrame
for name, group in grouped:
    # Group the DataFrame by 'year' and 'sector-name' and sum the 'value' column
    group = group.groupby(['year', 'sector-name'])['value'].sum().reset_index()
    
    # Rename the 'fuel-name' to 'Total'
    group['fuel-name'] = 'Total'
    
    # Reorder the columns to match the original DataFrame
    group = group[['year', 'sector-name', 'fuel-name', 'value']]
    
    dfs_sector_name[name] = group

# Print the DataFrames for each unique combination of 'sector-name'
for name, df_group in dfs_sector_name.items():
    print("DataFrame for", name)
    print(df_group)
    print()

DataFrame for Commercial carbon dioxide emissions
    year                          sector-name fuel-name       value
0   1970  Commercial carbon dioxide emissions     Total  524.952433
1   1971  Commercial carbon dioxide emissions     Total  533.704471
2   1972  Commercial carbon dioxide emissions     Total  543.036232
3   1973  Commercial carbon dioxide emissions     Total  548.152104
4   1974  Commercial carbon dioxide emissions     Total  524.472206
5   1975  Commercial carbon dioxide emissions     Total  495.842203
6   1976  Commercial carbon dioxide emissions     Total  535.286695
7   1977  Commercial carbon dioxide emissions     Total  525.717476
8   1978  Commercial carbon dioxide emissions     Total  529.809257
9   1979  Commercial carbon dioxide emissions     Total  529.994150
10  1980  Commercial carbon dioxide emissions     Total  498.762521
11  1981  Commercial carbon dioxide emissions     Total  464.012750
12  1982  Commercial carbon dioxide emissions     Total  465.078469
13  1983  Commercial carbon dioxide emissions     Total  467.359499
14  1984  Commercial carbon dioxide emissions     Total  487.172277
15  1985  Commercial carbon dioxide emissions     Total  449.869462
16  1986  Commercial carbon dioxide emissions     Total  448.596522
17  1987  Commercial carbon dioxide emissions     Total  454.374918
18  1988  Commercial carbon dioxide emissions     Total  476.521482
19  1989  Commercial carbon dioxide emissions     Total  470.481046
20  1990  Commercial carbon dioxide emissions     Total  454.083712
21  1991  Commercial carbon dioxide emissions     Total  455.504004
22  1992  Commercial carbon dioxide emissions     Total  457.831961
23  1993  Commercial carbon dioxide emissions     Total  453.450935
24  1994  Commercial carbon dioxide emissions     Total  458.016279
25  1995  Commercial carbon dioxide emissions     Total  464.534423
26  1996  Commercial carbon dioxide emissions     Total  482.136891
27  1997  Commercial carbon dioxide emissions     Total  482.424066
28  1998  Commercial carbon dioxide emissions     Total  448.603636
29  1999  Commercial carbon dioxide emissions     Total  452.895111
30  2000  Commercial carbon dioxide emissions     Total  479.193051
31  2001  Commercial carbon dioxide emissions     Total  460.682355
32  2002  Commercial carbon dioxide emissions     Total  463.416120
33  2003  Commercial carbon dioxide emissions     Total  484.575658
34  2004  Commercial carbon dioxide emissions     Total  477.436230
35  2005  Commercial carbon dioxide emissions     Total  455.588962
36  2006  Commercial carbon dioxide emissions     Total  416.387858
37  2007  Commercial carbon dioxide emissions     Total  434.887709
38  2008  Commercial carbon dioxide emissions     Total  452.828748
39  2009  Commercial carbon dioxide emissions     Total  448.055358
40  2010  Commercial carbon dioxide emissions     Total  443.079027
41  2011  Commercial carbon dioxide emissions     Total  445.006413
42  2012  Commercial carbon dioxide emissions     Total  403.357829
43  2013  Commercial carbon dioxide emissions     Total  446.903892
44  2014  Commercial carbon dioxide emissions     Total  469.613644
45  2015  Commercial carbon dioxide emissions     Total  483.827425
46  2016  Commercial carbon dioxide emissions     Total  467.921189
47  2017  Commercial carbon dioxide emissions     Total  471.383518
48  2018  Commercial carbon dioxide emissions     Total  512.797113
49  2019  Commercial carbon dioxide emissions     Total  514.730157
50  2020  Commercial carbon dioxide emissions     Total  471.587607
51  2021  Commercial carbon dioxide emissions     Total  495.812665

DataFrame for Electric Power carbon dioxide emissions
    year                              sector-name fuel-name        value
0   1970  Electric Power carbon dioxide emissions     Total  2122.880366
1   1971  Electric Power carbon dioxide emissions     Total  2197.656773
2   1972  Electric Power carbon dioxide emissions     Total  2383.076058
3   1973  Electric Power carbon dioxide emissions     Total  2566.447440
4   1974  Electric Power carbon dioxide emissions     Total  2498.006026
5   1975  Electric Power carbon dioxide emissions     Total  2487.013548
6   1976  Electric Power carbon dioxide emissions     Total  2703.611561
7   1977  Electric Power carbon dioxide emissions     Total  2879.498190
8   1978  Electric Power carbon dioxide emissions     Total  2894.706729
9   1979  Electric Power carbon dioxide emissions     Total  3016.604041
10  1980  Electric Power carbon dioxide emissions     Total  3109.892693
11  1981  Electric Power carbon dioxide emissions     Total  3129.793197
12  1982  Electric Power carbon dioxide emissions     Total  2973.778117
13  1983  Electric Power carbon dioxide emissions     Total  3057.463269
14  1984  Electric Power carbon dioxide emissions     Total  3190.157626
15  1985  Electric Power carbon dioxide emissions     Total  3273.440794
16  1986  Electric Power carbon dioxide emissions     Total  3246.229950
17  1987  Electric Power carbon dioxide emissions     Total  3375.460409
18  1988  Electric Power carbon dioxide emissions     Total  3544.337740
19  1989  Electric Power carbon dioxide emissions     Total  3664.005759
20  1990  Electric Power carbon dioxide emissions     Total  3641.405941
21  1991  Electric Power carbon dioxide emissions     Total  3635.915536
22  1992  Electric Power carbon dioxide emissions     Total  3662.271396
23  1993  Electric Power carbon dioxide emissions     Total  3813.542926
24  1994  Electric Power carbon dioxide emissions     Total  3862.160757
25  1995  Electric Power carbon dioxide emissions     Total  3896.292227
26  1996  Electric Power carbon dioxide emissions     Total  4041.422063
27  1997  Electric Power carbon dioxide emissions     Total  4176.092507
28  1998  Electric Power carbon dioxide emissions     Total  4354.256748
29  1999  Electric Power carbon dioxide emissions     Total  4379.981421
30  2000  Electric Power carbon dioxide emissions     Total  4593.604268
31  2001  Electric Power carbon dioxide emissions     Total  4518.119350
32  2002  Electric Power carbon dioxide emissions     Total  4545.787928
33  2003  Electric Power carbon dioxide emissions     Total  4608.072577
34  2004  Electric Power carbon dioxide emissions     Total  4669.995246
35  2005  Electric Power carbon dioxide emissions     Total  4801.693850
36  2006  Electric Power carbon dioxide emissions     Total  4690.095878
37  2007  Electric Power carbon dioxide emissions     Total  4822.661217
38  2008  Electric Power carbon dioxide emissions     Total  4719.785594
39  2009  Electric Power carbon dioxide emissions     Total  4291.881600
40  2010  Electric Power carbon dioxide emissions     Total  4519.703315
41  2011  Electric Power carbon dioxide emissions     Total  4318.229638
42  2012  Electric Power carbon dioxide emissions     Total  4048.420363
43  2013  Electric Power carbon dioxide emissions     Total  4077.898010
44  2014  Electric Power carbon dioxide emissions     Total  4076.013505
45  2015  Electric Power carbon dioxide emissions     Total  3802.693130
46  2016  Electric Power carbon dioxide emissions     Total  3619.234689
47  2017  Electric Power carbon dioxide emissions     Total  3465.440881
48  2018  Electric Power carbon dioxide emissions     Total  3509.389641
49  2019  Electric Power carbon dioxide emissions     Total  3216.273155
50  2020  Electric Power carbon dioxide emissions     Total  2880.864213
51  2021  Electric Power carbon dioxide emissions     Total  3084.080959

DataFrame for Industrial carbon dioxide emissions
    year                          sector-name fuel-name        value
0   1970  Industrial carbon dioxide emissions     Total  2640.355565
1   1971  Industrial carbon dioxide emissions     Total  2546.852979
2   1972  Industrial carbon dioxide emissions     Total  2627.657723
3   1973  Industrial carbon dioxide emissions     Total  2741.921674
4   1974  Industrial carbon dioxide emissions     Total  2607.819091
5   1975  Industrial carbon dioxide emissions     Total  2379.670547
6   1976  Industrial carbon dioxide emissions     Total  2492.945751
7   1977  Industrial carbon dioxide emissions     Total  2526.793507
8   1978  Industrial carbon dioxide emissions     Total  2480.167923
9   1979  Industrial carbon dioxide emissions     Total  2561.244604
10  1980  Industrial carbon dioxide emissions     Total  2336.933663
11  1981  Industrial carbon dioxide emissions     Total  2187.065039
12  1982  Industrial carbon dioxide emissions     Total  1924.193036
13  1983  Industrial carbon dioxide emissions     Total  1841.574906
14  1984  Industrial carbon dioxide emissions     Total  2028.458639
15  1985  Industrial carbon dioxide emissions     Total  1937.573639
16  1986  Industrial carbon dioxide emissions     Total  1889.569717
17  1987  Industrial carbon dioxide emissions     Total  1952.958580
18  1988  Industrial carbon dioxide emissions     Total  2057.823180
19  1989  Industrial carbon dioxide emissions     Total  2059.939625
20  1990  Industrial carbon dioxide emissions     Total  2108.518608
21  1991  Industrial carbon dioxide emissions     Total  2042.128966
22  1992  Industrial carbon dioxide emissions     Total  2137.969344
23  1993  Industrial carbon dioxide emissions     Total  2121.887519
24  1994  Industrial carbon dioxide emissions     Total  2150.403357
25  1995  Industrial carbon dioxide emissions     Total  2173.382704
26  1996  Industrial carbon dioxide emissions     Total  2249.772298
27  1997  Industrial carbon dioxide emissions     Total  2257.225950
28  1998  Industrial carbon dioxide emissions     Total  2177.607696
29  1999  Industrial carbon dioxide emissions     Total  2141.364189
30  2000  Industrial carbon dioxide emissions     Total  2128.362129
31  2001  Industrial carbon dioxide emissions     Total  2085.384810
32  2002  Industrial carbon dioxide emissions     Total  2051.148026
33  2003  Industrial carbon dioxide emissions     Total  2039.867739
34  2004  Industrial carbon dioxide emissions     Total  2099.981090
35  2005  Industrial carbon dioxide emissions     Total  2014.756219
36  2006  Industrial carbon dioxide emissions     Total  2020.428078
37  2007  Industrial carbon dioxide emissions     Total  2002.537159
38  2008  Industrial carbon dioxide emissions     Total  1933.737484
39  2009  Industrial carbon dioxide emissions     Total  1708.897325
40  2010  Industrial carbon dioxide emissions     Total  1842.823351
41  2011  Industrial carbon dioxide emissions     Total  1849.215164
42  2012  Industrial carbon dioxide emissions     Total  1873.046986
43  2013  Industrial carbon dioxide emissions     Total  1916.289557
44  2014  Industrial carbon dioxide emissions     Total  1938.377173
45  2015  Industrial carbon dioxide emissions     Total  1901.008840
46  2016  Industrial carbon dioxide emissions     Total  1897.209399
47  2017  Industrial carbon dioxide emissions     Total  1935.695108
48  2018  Industrial carbon dioxide emissions     Total  2009.632886
49  2019  Industrial carbon dioxide emissions     Total  2013.284413
50  2020  Industrial carbon dioxide emissions     Total  1898.128137
51  2021  Industrial carbon dioxide emissions     Total  1960.369449

DataFrame for Residential carbon dioxide emissions
    year                           sector-name fuel-name       value
0   1970  Residential carbon dioxide emissions     Total  955.538394
1   1971  Residential carbon dioxide emissions     Total  966.514498
2   1972  Residential carbon dioxide emissions     Total  990.067779
3   1973  Residential carbon dioxide emissions     Total  949.582197
4   1974  Residential carbon dioxide emissions     Total  900.987199
5   1975  Residential carbon dioxide emissions     Total  899.900507
6   1976  Residential carbon dioxide emissions     Total  945.132872
7   1977  Residential carbon dioxide emissions     Total  917.072452
8   1978  Residential carbon dioxide emissions     Total  912.628744
9   1979  Residential carbon dioxide emissions     Total  845.760394
10  1980  Residential carbon dioxide emissions     Total  770.299655
11  1981  Residential carbon dioxide emissions     Total  718.852439
12  1982  Residential carbon dioxide emissions     Total  715.432611
13  1983  Residential carbon dioxide emissions     Total  677.145313
14  1984  Residential carbon dioxide emissions     Total  724.429863
15  1985  Residential carbon dioxide emissions     Total  715.998096
16  1986  Residential carbon dioxide emissions     Total  698.703342
17  1987  Residential carbon dioxide emissions     Total  709.064810
18  1988  Residential carbon dioxide emissions     Total  751.579967
19  1989  Residential carbon dioxide emissions     Total  765.263420
20  1990  Residential carbon dioxide emissions     Total  683.523662
21  1991  Residential carbon dioxide emissions     Total  697.021138
22  1992  Residential carbon dioxide emissions     Total  716.624591
23  1993  Residential carbon dioxide emissions     Total  749.638885
24  1994  Residential carbon dioxide emissions     Total  731.805734
25  1995  Residential carbon dioxide emissions     Total  726.452501
26  1996  Residential carbon dioxide emissions     Total  784.007227
27  1997  Residential carbon dioxide emissions     Total  746.946421
28  1998  Residential carbon dioxide emissions     Total  680.643334
29  1999  Residential carbon dioxide emissions     Total  722.475387
30  2000  Residential carbon dioxide emissions     Total  762.502542
31  2001  Residential carbon dioxide emissions     Total  737.476855
32  2002  Residential carbon dioxide emissions     Total  738.160919
33  2003  Residential carbon dioxide emissions     Total  774.233858
34  2004  Residential carbon dioxide emissions     Total  746.804376
35  2005  Residential carbon dioxide emissions     Total  731.594446
36  2006  Residential carbon dioxide emissions     Total  648.144233
37  2007  Residential carbon dioxide emissions     Total  690.041710
38  2008  Residential carbon dioxide emissions     Total  716.125792
39  2009  Residential carbon dioxide emissions     Total  679.144705
40  2010  Residential carbon dioxide emissions     Total  673.168838
41  2011  Residential carbon dioxide emissions     Total  653.630783
42  2012  Residential carbon dioxide emissions     Total  573.591847
43  2013  Residential carbon dioxide emissions     Total  666.399636
44  2014  Residential carbon dioxide emissions     Total  699.673933
45  2015  Residential carbon dioxide emissions     Total  646.485009
46  2016  Residential carbon dioxide emissions     Total  599.169065
47  2017  Residential carbon dioxide emissions     Total  605.335002
48  2018  Residential carbon dioxide emissions     Total  690.452603
49  2019  Residential carbon dioxide emissions     Total  695.763574
50  2020  Residential carbon dioxide emissions     Total  640.181573
51  2021  Residential carbon dioxide emissions     Total  652.485586

DataFrame for Transportation carbon dioxide emissions
    year                              sector-name fuel-name        value
0   1970  Transportation carbon dioxide emissions     Total  2263.336813
1   1971  Transportation carbon dioxide emissions     Total  2352.662168
2   1972  Transportation carbon dioxide emissions     Total  2492.989811
3   1973  Transportation carbon dioxide emissions     Total  2624.260159
4   1974  Transportation carbon dioxide emissions     Total  2556.368151
5   1975  Transportation carbon dioxide emissions     Total  2577.130243
6   1976  Transportation carbon dioxide emissions     Total  2700.961919
7   1977  Transportation carbon dioxide emissions     Total  2805.805592
8   1978  Transportation carbon dioxide emissions     Total  2920.220529
9   1979  Transportation carbon dioxide emissions     Total  2899.750450
10  1980  Transportation carbon dioxide emissions     Total  2789.706724
11  1981  Transportation carbon dioxide emissions     Total  2761.261172
12  1982  Transportation carbon dioxide emissions     Total  2698.007231
13  1983  Transportation carbon dioxide emissions     Total  2707.416975
14  1984  Transportation carbon dioxide emissions     Total  2770.797704
15  1985  Transportation carbon dioxide emissions     Total  2833.080796
16  1986  Transportation carbon dioxide emissions     Total  2932.293175
17  1987  Transportation carbon dioxide emissions     Total  3024.922701
18  1988  Transportation carbon dioxide emissions     Total  3143.865763
19  1989  Transportation carbon dioxide emissions     Total  3165.742537
20  1990  Transportation carbon dioxide emissions     Total  3158.617365
21  1991  Transportation carbon dioxide emissions     Total  3114.038523
22  1992  Transportation carbon dioxide emissions     Total  3153.668515
23  1993  Transportation carbon dioxide emissions     Total  3194.926637
24  1994  Transportation carbon dioxide emissions     Total  3280.664965
25  1995  Transportation carbon dioxide emissions     Total  3351.855474
26  1996  Transportation carbon dioxide emissions     Total  3451.104988
27  1997  Transportation carbon dioxide emissions     Total  3491.039804
28  1998  Transportation carbon dioxide emissions     Total  3564.888343
29  1999  Transportation carbon dioxide emissions     Total  3657.169779
30  2000  Transportation carbon dioxide emissions     Total  3768.910461
31  2001  Transportation carbon dioxide emissions     Total  3711.563437
32  2002  Transportation carbon dioxide emissions     Total  3790.961793
33  2003  Transportation carbon dioxide emissions     Total  3825.198300
34  2004  Transportation carbon dioxide emissions     Total  3934.943640
35  2005  Transportation carbon dioxide emissions     Total  3976.275391
36  2006  Transportation carbon dioxide emissions     Total  4039.056250
37  2007  Transportation carbon dioxide emissions     Total  4044.474542
38  2008  Transportation carbon dioxide emissions     Total  3784.660595
39  2009  Transportation carbon dioxide emissions     Total  3663.563918
40  2010  Transportation carbon dioxide emissions     Total  3691.595412
41  2011  Transportation carbon dioxide emissions     Total  3633.718334
42  2012  Transportation carbon dioxide emissions     Total  3560.770465
43  2013  Transportation carbon dioxide emissions     Total  3614.691326
44  2014  Transportation carbon dioxide emissions     Total  3650.893114
45  2015  Transportation carbon dioxide emissions     Total  3700.757759
46  2016  Transportation carbon dioxide emissions     Total  3776.025765
47  2017  Transportation carbon dioxide emissions     Total  3809.483170
48  2018  Transportation carbon dioxide emissions     Total  3868.898393
49  2019  Transportation carbon dioxide emissions     Total  3879.401066
50  2020  Transportation carbon dioxide emissions     Total  3298.672725
51  2021  Transportation carbon dioxide emissions     Total  3629.705992

In [89]:
# Group the DataFrame by 'fuel-name'
grouped = pivot_df_sorted.groupby(['fuel-name'])

# Create a dictionary to store the DataFrames
dfs_fuel_name = {}

# Iterate over each group and store the corresponding DataFrame
for name, group in grouped:
    # Group the DataFrame by 'year' and 'fuel-name' and sum the 'value' column
    group = group.groupby(['year', 'fuel-name'])['value'].sum().reset_index()
    
    # Rename the 'fuel-name' to 'Total'
    group['sector-name'] = 'Total'
    
    # Reorder the columns to match the original DataFrame
    group = group[['year', 'sector-name', 'fuel-name', 'value']]
    
    dfs_fuel_name[name] = group

# Print the DataFrames for each unique combination of 'fuel-name'
for name, df_group in dfs_fuel_name.items():
    print("DataFrame for", name)
    print(df_group)
    print()

DataFrame for Coal
    year sector-name fuel-name        value
0   1970       Total      Coal  2311.126560
1   1971       Total      Coal  2187.743724
2   1972       Total      Coal  2283.000112
3   1973       Total      Coal  2443.490583
4   1974       Total      Coal  2386.105741
5   1975       Total      Coal  2388.027333
6   1976       Total      Coal  2563.195745
7   1977       Total      Coal  2627.566307
8   1978       Total      Coal  2602.873837
9   1979       Total      Coal  2843.300211
10  1980       Total      Coal  2924.836740
11  1981       Total      Coal  3016.997098
12  1982       Total      Coal  2894.453933
13  1983       Total      Coal  3009.112576
14  1984       Total      Coal  3225.430596
15  1985       Total      Coal  3326.168963
16  1986       Total      Coal  3272.427202
17  1987       Total      Coal  3406.837920
18  1988       Total      Coal  3584.902972
19  1989       Total      Coal  3617.355257
20  1990       Total      Coal  3638.854087
21  1991       Total      Coal  3610.042113
22  1992       Total      Coal  3635.494141
23  1993       Total      Coal  3758.272863
24  1994       Total      Coal  3770.835057
25  1995       Total      Coal  3813.294965
26  1996       Total      Coal  3984.510120
27  1997       Total      Coal  4067.450536
28  1998       Total      Coal  4098.322338
29  1999       Total      Coal  4102.382660
30  2000       Total      Coal  4293.881862
31  2001       Total      Coal  4167.281271
32  2002       Total      Coal  4172.197235
33  2003       Total      Coal  4257.868684
34  2004       Total      Coal  4285.010742
35  2005       Total      Coal  4350.835494
36  2006       Total      Coal  4278.512602
37  2007       Total      Coal  4336.251597
38  2008       Total      Coal  4268.147608
39  2009       Total      Coal  3756.028591
40  2010       Total      Coal  3972.695120
41  2011       Total      Coal  3750.400971
42  2012       Total      Coal  3315.753311
43  2013       Total      Coal  3440.059630
44  2014       Total      Coal  3431.628172
45  2015       Total      Coal  2968.063701
46  2016       Total      Coal  2715.282356
47  2017       Total      Coal  2642.989821
48  2018       Total      Coal  2531.149755
49  2019       Total      Coal  2160.215370
50  2020       Total      Coal  1755.849253
51  2021       Total      Coal  2017.214715

DataFrame for Natural Gas
    year sector-name    fuel-name        value
0   1970       Total  Natural Gas  2255.982068
1   1971       Total  Natural Gas  2325.650502
2   1972       Total  Natural Gas  2359.147560
3   1973       Total  Natural Gas  2347.243536
4   1974       Total  Natural Gas  2257.439848
5   1975       Total  Natural Gas  2078.381797
6   1976       Total  Natural Gas  2120.151965
7   1977       Total  Natural Gas  2077.356991
8   1978       Total  Natural Gas  2087.829825
9   1979       Total  Natural Gas  2153.663515
10  1980       Total  Natural Gas  2122.277028
11  1981       Total  Natural Gas  2074.575749
12  1982       Total  Natural Gas  1930.018853
13  1983       Total  Natural Gas  1807.680903
14  1984       Total  Natural Gas  1927.212791
15  1985       Total  Natural Gas  1858.967229
16  1986       Total  Natural Gas  1741.496678
17  1987       Total  Natural Gas  1847.916075
18  1988       Total  Natural Gas  1932.385636
19  1989       Total  Natural Gas  2052.654898
20  1990       Total  Natural Gas  2054.802853
21  1991       Total  Natural Gas  2094.725712
22  1992       Total  Natural Gas  2166.783643
23  1993       Total  Natural Gas  2224.159334
24  1994       Total  Natural Gas  2276.170175
25  1995       Total  Natural Gas  2377.655807
26  1996       Total  Natural Gas  2421.771807
27  1997       Total  Natural Gas  2444.038137
28  1998       Total  Natural Gas  2392.811083
29  1999       Total  Natural Gas  2397.608075
30  2000       Total  Natural Gas  2490.053565
31  2001       Total  Natural Gas  2375.661077
32  2002       Total  Natural Gas  2459.132773
33  2003       Total  Natural Gas  2388.256857
34  2004       Total  Natural Gas  2404.553176
35  2005       Total  Natural Gas  2368.844072
36  2006       Total  Natural Gas  2336.113530
37  2007       Total  Natural Gas  2487.102307
38  2008       Total  Natural Gas  2502.234159
39  2009       Total  Natural Gas  2458.503330
40  2010       Total  Natural Gas  2580.564588
41  2011       Total  Natural Gas  2620.021498
42  2012       Total  Natural Gas  2733.762409
43  2013       Total  Natural Gas  2805.410158
44  2014       Total  Natural Gas  2864.938273
45  2015       Total  Natural Gas  2945.986636
46  2016       Total  Natural Gas  2967.567874
47  2017       Total  Natural Gas  2931.829023
48  2018       Total  Natural Gas  3258.258351
49  2019       Total  Natural Gas  3370.235498
50  2020       Total  Natural Gas  3300.450490
51  2021       Total  Natural Gas  3309.710671

DataFrame for Petroleum
    year sector-name  fuel-name        value
0   1970       Total  Petroleum  3939.954943
1   1971       Total  Petroleum  4083.996663
2   1972       Total  Petroleum  4394.679931
3   1973       Total  Petroleum  4639.629455
4   1974       Total  Petroleum  4444.107084
5   1975       Total  Petroleum  4373.147918
6   1976       Total  Petroleum  4694.591088
7   1977       Total  Petroleum  4949.963919
8   1978       Total  Petroleum  5046.829520
9   1979       Total  Petroleum  4856.389913
10  1980       Total  Petroleum  4458.481488
11  1981       Total  Petroleum  4169.411750
12  1982       Total  Petroleum  3952.016678
13  1983       Total  Petroleum  3934.166483
14  1984       Total  Petroleum  4048.372722
15  1985       Total  Petroleum  4024.826595
16  1986       Total  Petroleum  4201.468826
17  1987       Total  Petroleum  4262.027423
18  1988       Total  Petroleum  4456.839524
19  1989       Total  Petroleum  4455.422232
20  1990       Total  Petroleum  4352.492348
21  1991       Total  Petroleum  4239.840342
22  1992       Total  Petroleum  4326.088023
23  1993       Total  Petroleum  4351.014705
24  1994       Total  Petroleum  4436.045860
25  1995       Total  Petroleum  4421.566557
26  1996       Total  Petroleum  4602.161540
27  1997       Total  Petroleum  4642.240075
28  1998       Total  Petroleum  4734.866336
29  1999       Total  Petroleum  4853.895152
30  2000       Total  Petroleum  4948.637024
31  2001       Total  Petroleum  4970.284459
32  2002       Total  Petroleum  4958.144778
33  2003       Total  Petroleum  5085.822591
34  2004       Total  Petroleum  5239.596664
35  2005       Total  Petroleum  5260.229302
36  2006       Total  Petroleum  5199.486165
37  2007       Total  Petroleum  5171.248433
38  2008       Total  Petroleum  4836.756446
39  2009       Total  Petroleum  4577.010985
40  2010       Total  Petroleum  4617.110235
41  2011       Total  Petroleum  4529.377863
42  2012       Total  Petroleum  4409.671770
43  2013       Total  Petroleum  4476.712633
44  2014       Total  Petroleum  4538.004924
45  2015       Total  Petroleum  4620.721826
46  2016       Total  Petroleum  4676.709877
47  2017       Total  Petroleum  4712.518835
48  2018       Total  Petroleum  4801.762530
49  2019       Total  Petroleum  4789.001497
50  2020       Total  Petroleum  4133.134512
51  2021       Total  Petroleum  4495.529265

In [86]:
# # Group the DataFrame by 'sector-name' and 'fuel-name'
# grouped = pivot_df_sorted.groupby(['sector-name', 'fuel-name'])

# # Create a dictionary to store the DataFrames
# dfs = {}

# # Iterate over each group and store the corresponding DataFrame
# for name, group in grouped:
#     dfs[name] = group

# # Print the DataFrames for each unique combination of 'sector-name' and 'fuel-name'
# for name, df_group in dfs.items():
#     print("DataFrame for", name)
#     print(df_group)
#     print()

In [90]:
dfs = dfs_sector_name
dfs.update(dfs_fuel_name)

# Print the DataFrames for each unique combination of 'sector-name' and 'fuel-name'
for name, df_group in dfs.items():
    print("DataFrame for", name)
    print(df_group)
    print()

DataFrame for Commercial carbon dioxide emissions
    year                          sector-name fuel-name       value
0   1970  Commercial carbon dioxide emissions     Total  524.952433
1   1971  Commercial carbon dioxide emissions     Total  533.704471
2   1972  Commercial carbon dioxide emissions     Total  543.036232
3   1973  Commercial carbon dioxide emissions     Total  548.152104
4   1974  Commercial carbon dioxide emissions     Total  524.472206
5   1975  Commercial carbon dioxide emissions     Total  495.842203
6   1976  Commercial carbon dioxide emissions     Total  535.286695
7   1977  Commercial carbon dioxide emissions     Total  525.717476
8   1978  Commercial carbon dioxide emissions     Total  529.809257
9   1979  Commercial carbon dioxide emissions     Total  529.994150
10  1980  Commercial carbon dioxide emissions     Total  498.762521
11  1981  Commercial carbon dioxide emissions     Total  464.012750
12  1982  Commercial carbon dioxide emissions     Total  465.078469
13  1983  Commercial carbon dioxide emissions     Total  467.359499
14  1984  Commercial carbon dioxide emissions     Total  487.172277
15  1985  Commercial carbon dioxide emissions     Total  449.869462
16  1986  Commercial carbon dioxide emissions     Total  448.596522
17  1987  Commercial carbon dioxide emissions     Total  454.374918
18  1988  Commercial carbon dioxide emissions     Total  476.521482
19  1989  Commercial carbon dioxide emissions     Total  470.481046
20  1990  Commercial carbon dioxide emissions     Total  454.083712
21  1991  Commercial carbon dioxide emissions     Total  455.504004
22  1992  Commercial carbon dioxide emissions     Total  457.831961
23  1993  Commercial carbon dioxide emissions     Total  453.450935
24  1994  Commercial carbon dioxide emissions     Total  458.016279
25  1995  Commercial carbon dioxide emissions     Total  464.534423
26  1996  Commercial carbon dioxide emissions     Total  482.136891
27  1997  Commercial carbon dioxide emissions     Total  482.424066
28  1998  Commercial carbon dioxide emissions     Total  448.603636
29  1999  Commercial carbon dioxide emissions     Total  452.895111
30  2000  Commercial carbon dioxide emissions     Total  479.193051
31  2001  Commercial carbon dioxide emissions     Total  460.682355
32  2002  Commercial carbon dioxide emissions     Total  463.416120
33  2003  Commercial carbon dioxide emissions     Total  484.575658
34  2004  Commercial carbon dioxide emissions     Total  477.436230
35  2005  Commercial carbon dioxide emissions     Total  455.588962
36  2006  Commercial carbon dioxide emissions     Total  416.387858
37  2007  Commercial carbon dioxide emissions     Total  434.887709
38  2008  Commercial carbon dioxide emissions     Total  452.828748
39  2009  Commercial carbon dioxide emissions     Total  448.055358
40  2010  Commercial carbon dioxide emissions     Total  443.079027
41  2011  Commercial carbon dioxide emissions     Total  445.006413
42  2012  Commercial carbon dioxide emissions     Total  403.357829
43  2013  Commercial carbon dioxide emissions     Total  446.903892
44  2014  Commercial carbon dioxide emissions     Total  469.613644
45  2015  Commercial carbon dioxide emissions     Total  483.827425
46  2016  Commercial carbon dioxide emissions     Total  467.921189
47  2017  Commercial carbon dioxide emissions     Total  471.383518
48  2018  Commercial carbon dioxide emissions     Total  512.797113
49  2019  Commercial carbon dioxide emissions     Total  514.730157
50  2020  Commercial carbon dioxide emissions     Total  471.587607
51  2021  Commercial carbon dioxide emissions     Total  495.812665

DataFrame for Electric Power carbon dioxide emissions
    year                              sector-name fuel-name        value
0   1970  Electric Power carbon dioxide emissions     Total  2122.880366
1   1971  Electric Power carbon dioxide emissions     Total  2197.656773
2   1972  Electric Power carbon dioxide emissions     Total  2383.076058
3   1973  Electric Power carbon dioxide emissions     Total  2566.447440
4   1974  Electric Power carbon dioxide emissions     Total  2498.006026
5   1975  Electric Power carbon dioxide emissions     Total  2487.013548
6   1976  Electric Power carbon dioxide emissions     Total  2703.611561
7   1977  Electric Power carbon dioxide emissions     Total  2879.498190
8   1978  Electric Power carbon dioxide emissions     Total  2894.706729
9   1979  Electric Power carbon dioxide emissions     Total  3016.604041
10  1980  Electric Power carbon dioxide emissions     Total  3109.892693
11  1981  Electric Power carbon dioxide emissions     Total  3129.793197
12  1982  Electric Power carbon dioxide emissions     Total  2973.778117
13  1983  Electric Power carbon dioxide emissions     Total  3057.463269
14  1984  Electric Power carbon dioxide emissions     Total  3190.157626
15  1985  Electric Power carbon dioxide emissions     Total  3273.440794
16  1986  Electric Power carbon dioxide emissions     Total  3246.229950
17  1987  Electric Power carbon dioxide emissions     Total  3375.460409
18  1988  Electric Power carbon dioxide emissions     Total  3544.337740
19  1989  Electric Power carbon dioxide emissions     Total  3664.005759
20  1990  Electric Power carbon dioxide emissions     Total  3641.405941
21  1991  Electric Power carbon dioxide emissions     Total  3635.915536
22  1992  Electric Power carbon dioxide emissions     Total  3662.271396
23  1993  Electric Power carbon dioxide emissions     Total  3813.542926
24  1994  Electric Power carbon dioxide emissions     Total  3862.160757
25  1995  Electric Power carbon dioxide emissions     Total  3896.292227
26  1996  Electric Power carbon dioxide emissions     Total  4041.422063
27  1997  Electric Power carbon dioxide emissions     Total  4176.092507
28  1998  Electric Power carbon dioxide emissions     Total  4354.256748
29  1999  Electric Power carbon dioxide emissions     Total  4379.981421
30  2000  Electric Power carbon dioxide emissions     Total  4593.604268
31  2001  Electric Power carbon dioxide emissions     Total  4518.119350
32  2002  Electric Power carbon dioxide emissions     Total  4545.787928
33  2003  Electric Power carbon dioxide emissions     Total  4608.072577
34  2004  Electric Power carbon dioxide emissions     Total  4669.995246
35  2005  Electric Power carbon dioxide emissions     Total  4801.693850
36  2006  Electric Power carbon dioxide emissions     Total  4690.095878
37  2007  Electric Power carbon dioxide emissions     Total  4822.661217
38  2008  Electric Power carbon dioxide emissions     Total  4719.785594
39  2009  Electric Power carbon dioxide emissions     Total  4291.881600
40  2010  Electric Power carbon dioxide emissions     Total  4519.703315
41  2011  Electric Power carbon dioxide emissions     Total  4318.229638
42  2012  Electric Power carbon dioxide emissions     Total  4048.420363
43  2013  Electric Power carbon dioxide emissions     Total  4077.898010
44  2014  Electric Power carbon dioxide emissions     Total  4076.013505
45  2015  Electric Power carbon dioxide emissions     Total  3802.693130
46  2016  Electric Power carbon dioxide emissions     Total  3619.234689
47  2017  Electric Power carbon dioxide emissions     Total  3465.440881
48  2018  Electric Power carbon dioxide emissions     Total  3509.389641
49  2019  Electric Power carbon dioxide emissions     Total  3216.273155
50  2020  Electric Power carbon dioxide emissions     Total  2880.864213
51  2021  Electric Power carbon dioxide emissions     Total  3084.080959

DataFrame for Industrial carbon dioxide emissions
    year                          sector-name fuel-name        value
0   1970  Industrial carbon dioxide emissions     Total  2640.355565
1   1971  Industrial carbon dioxide emissions     Total  2546.852979
2   1972  Industrial carbon dioxide emissions     Total  2627.657723
3   1973  Industrial carbon dioxide emissions     Total  2741.921674
4   1974  Industrial carbon dioxide emissions     Total  2607.819091
5   1975  Industrial carbon dioxide emissions     Total  2379.670547
6   1976  Industrial carbon dioxide emissions     Total  2492.945751
7   1977  Industrial carbon dioxide emissions     Total  2526.793507
8   1978  Industrial carbon dioxide emissions     Total  2480.167923
9   1979  Industrial carbon dioxide emissions     Total  2561.244604
10  1980  Industrial carbon dioxide emissions     Total  2336.933663
11  1981  Industrial carbon dioxide emissions     Total  2187.065039
12  1982  Industrial carbon dioxide emissions     Total  1924.193036
13  1983  Industrial carbon dioxide emissions     Total  1841.574906
14  1984  Industrial carbon dioxide emissions     Total  2028.458639
15  1985  Industrial carbon dioxide emissions     Total  1937.573639
16  1986  Industrial carbon dioxide emissions     Total  1889.569717
17  1987  Industrial carbon dioxide emissions     Total  1952.958580
18  1988  Industrial carbon dioxide emissions     Total  2057.823180
19  1989  Industrial carbon dioxide emissions     Total  2059.939625
20  1990  Industrial carbon dioxide emissions     Total  2108.518608
21  1991  Industrial carbon dioxide emissions     Total  2042.128966
22  1992  Industrial carbon dioxide emissions     Total  2137.969344
23  1993  Industrial carbon dioxide emissions     Total  2121.887519
24  1994  Industrial carbon dioxide emissions     Total  2150.403357
25  1995  Industrial carbon dioxide emissions     Total  2173.382704
26  1996  Industrial carbon dioxide emissions     Total  2249.772298
27  1997  Industrial carbon dioxide emissions     Total  2257.225950
28  1998  Industrial carbon dioxide emissions     Total  2177.607696
29  1999  Industrial carbon dioxide emissions     Total  2141.364189
30  2000  Industrial carbon dioxide emissions     Total  2128.362129
31  2001  Industrial carbon dioxide emissions     Total  2085.384810
32  2002  Industrial carbon dioxide emissions     Total  2051.148026
33  2003  Industrial carbon dioxide emissions     Total  2039.867739
34  2004  Industrial carbon dioxide emissions     Total  2099.981090
35  2005  Industrial carbon dioxide emissions     Total  2014.756219
36  2006  Industrial carbon dioxide emissions     Total  2020.428078
37  2007  Industrial carbon dioxide emissions     Total  2002.537159
38  2008  Industrial carbon dioxide emissions     Total  1933.737484
39  2009  Industrial carbon dioxide emissions     Total  1708.897325
40  2010  Industrial carbon dioxide emissions     Total  1842.823351
41  2011  Industrial carbon dioxide emissions     Total  1849.215164
42  2012  Industrial carbon dioxide emissions     Total  1873.046986
43  2013  Industrial carbon dioxide emissions     Total  1916.289557
44  2014  Industrial carbon dioxide emissions     Total  1938.377173
45  2015  Industrial carbon dioxide emissions     Total  1901.008840
46  2016  Industrial carbon dioxide emissions     Total  1897.209399
47  2017  Industrial carbon dioxide emissions     Total  1935.695108
48  2018  Industrial carbon dioxide emissions     Total  2009.632886
49  2019  Industrial carbon dioxide emissions     Total  2013.284413
50  2020  Industrial carbon dioxide emissions     Total  1898.128137
51  2021  Industrial carbon dioxide emissions     Total  1960.369449

DataFrame for Residential carbon dioxide emissions
    year                           sector-name fuel-name       value
0   1970  Residential carbon dioxide emissions     Total  955.538394
1   1971  Residential carbon dioxide emissions     Total  966.514498
2   1972  Residential carbon dioxide emissions     Total  990.067779
3   1973  Residential carbon dioxide emissions     Total  949.582197
4   1974  Residential carbon dioxide emissions     Total  900.987199
5   1975  Residential carbon dioxide emissions     Total  899.900507
6   1976  Residential carbon dioxide emissions     Total  945.132872
7   1977  Residential carbon dioxide emissions     Total  917.072452
8   1978  Residential carbon dioxide emissions     Total  912.628744
9   1979  Residential carbon dioxide emissions     Total  845.760394
10  1980  Residential carbon dioxide emissions     Total  770.299655
11  1981  Residential carbon dioxide emissions     Total  718.852439
12  1982  Residential carbon dioxide emissions     Total  715.432611
13  1983  Residential carbon dioxide emissions     Total  677.145313
14  1984  Residential carbon dioxide emissions     Total  724.429863
15  1985  Residential carbon dioxide emissions     Total  715.998096
16  1986  Residential carbon dioxide emissions     Total  698.703342
17  1987  Residential carbon dioxide emissions     Total  709.064810
18  1988  Residential carbon dioxide emissions     Total  751.579967
19  1989  Residential carbon dioxide emissions     Total  765.263420
20  1990  Residential carbon dioxide emissions     Total  683.523662
21  1991  Residential carbon dioxide emissions     Total  697.021138
22  1992  Residential carbon dioxide emissions     Total  716.624591
23  1993  Residential carbon dioxide emissions     Total  749.638885
24  1994  Residential carbon dioxide emissions     Total  731.805734
25  1995  Residential carbon dioxide emissions     Total  726.452501
26  1996  Residential carbon dioxide emissions     Total  784.007227
27  1997  Residential carbon dioxide emissions     Total  746.946421
28  1998  Residential carbon dioxide emissions     Total  680.643334
29  1999  Residential carbon dioxide emissions     Total  722.475387
30  2000  Residential carbon dioxide emissions     Total  762.502542
31  2001  Residential carbon dioxide emissions     Total  737.476855
32  2002  Residential carbon dioxide emissions     Total  738.160919
33  2003  Residential carbon dioxide emissions     Total  774.233858
34  2004  Residential carbon dioxide emissions     Total  746.804376
35  2005  Residential carbon dioxide emissions     Total  731.594446
36  2006  Residential carbon dioxide emissions     Total  648.144233
37  2007  Residential carbon dioxide emissions     Total  690.041710
38  2008  Residential carbon dioxide emissions     Total  716.125792
39  2009  Residential carbon dioxide emissions     Total  679.144705
40  2010  Residential carbon dioxide emissions     Total  673.168838
41  2011  Residential carbon dioxide emissions     Total  653.630783
42  2012  Residential carbon dioxide emissions     Total  573.591847
43  2013  Residential carbon dioxide emissions     Total  666.399636
44  2014  Residential carbon dioxide emissions     Total  699.673933
45  2015  Residential carbon dioxide emissions     Total  646.485009
46  2016  Residential carbon dioxide emissions     Total  599.169065
47  2017  Residential carbon dioxide emissions     Total  605.335002
48  2018  Residential carbon dioxide emissions     Total  690.452603
49  2019  Residential carbon dioxide emissions     Total  695.763574
50  2020  Residential carbon dioxide emissions     Total  640.181573
51  2021  Residential carbon dioxide emissions     Total  652.485586

DataFrame for Transportation carbon dioxide emissions
    year                              sector-name fuel-name        value
0   1970  Transportation carbon dioxide emissions     Total  2263.336813
1   1971  Transportation carbon dioxide emissions     Total  2352.662168
2   1972  Transportation carbon dioxide emissions     Total  2492.989811
3   1973  Transportation carbon dioxide emissions     Total  2624.260159
4   1974  Transportation carbon dioxide emissions     Total  2556.368151
5   1975  Transportation carbon dioxide emissions     Total  2577.130243
6   1976  Transportation carbon dioxide emissions     Total  2700.961919
7   1977  Transportation carbon dioxide emissions     Total  2805.805592
8   1978  Transportation carbon dioxide emissions     Total  2920.220529
9   1979  Transportation carbon dioxide emissions     Total  2899.750450
10  1980  Transportation carbon dioxide emissions     Total  2789.706724
11  1981  Transportation carbon dioxide emissions     Total  2761.261172
12  1982  Transportation carbon dioxide emissions     Total  2698.007231
13  1983  Transportation carbon dioxide emissions     Total  2707.416975
14  1984  Transportation carbon dioxide emissions     Total  2770.797704
15  1985  Transportation carbon dioxide emissions     Total  2833.080796
16  1986  Transportation carbon dioxide emissions     Total  2932.293175
17  1987  Transportation carbon dioxide emissions     Total  3024.922701
18  1988  Transportation carbon dioxide emissions     Total  3143.865763
19  1989  Transportation carbon dioxide emissions     Total  3165.742537
20  1990  Transportation carbon dioxide emissions     Total  3158.617365
21  1991  Transportation carbon dioxide emissions     Total  3114.038523
22  1992  Transportation carbon dioxide emissions     Total  3153.668515
23  1993  Transportation carbon dioxide emissions     Total  3194.926637
24  1994  Transportation carbon dioxide emissions     Total  3280.664965
25  1995  Transportation carbon dioxide emissions     Total  3351.855474
26  1996  Transportation carbon dioxide emissions     Total  3451.104988
27  1997  Transportation carbon dioxide emissions     Total  3491.039804
28  1998  Transportation carbon dioxide emissions     Total  3564.888343
29  1999  Transportation carbon dioxide emissions     Total  3657.169779
30  2000  Transportation carbon dioxide emissions     Total  3768.910461
31  2001  Transportation carbon dioxide emissions     Total  3711.563437
32  2002  Transportation carbon dioxide emissions     Total  3790.961793
33  2003  Transportation carbon dioxide emissions     Total  3825.198300
34  2004  Transportation carbon dioxide emissions     Total  3934.943640
35  2005  Transportation carbon dioxide emissions     Total  3976.275391
36  2006  Transportation carbon dioxide emissions     Total  4039.056250
37  2007  Transportation carbon dioxide emissions     Total  4044.474542
38  2008  Transportation carbon dioxide emissions     Total  3784.660595
39  2009  Transportation carbon dioxide emissions     Total  3663.563918
40  2010  Transportation carbon dioxide emissions     Total  3691.595412
41  2011  Transportation carbon dioxide emissions     Total  3633.718334
42  2012  Transportation carbon dioxide emissions     Total  3560.770465
43  2013  Transportation carbon dioxide emissions     Total  3614.691326
44  2014  Transportation carbon dioxide emissions     Total  3650.893114
45  2015  Transportation carbon dioxide emissions     Total  3700.757759
46  2016  Transportation carbon dioxide emissions     Total  3776.025765
47  2017  Transportation carbon dioxide emissions     Total  3809.483170
48  2018  Transportation carbon dioxide emissions     Total  3868.898393
49  2019  Transportation carbon dioxide emissions     Total  3879.401066
50  2020  Transportation carbon dioxide emissions     Total  3298.672725
51  2021  Transportation carbon dioxide emissions     Total  3629.705992

DataFrame for Coal
    year sector-name fuel-name        value
0   1970       Total      Coal  2311.126560
1   1971       Total      Coal  2187.743724
2   1972       Total      Coal  2283.000112
3   1973       Total      Coal  2443.490583
4   1974       Total      Coal  2386.105741
5   1975       Total      Coal  2388.027333
6   1976       Total      Coal  2563.195745
7   1977       Total      Coal  2627.566307
8   1978       Total      Coal  2602.873837
9   1979       Total      Coal  2843.300211
10  1980       Total      Coal  2924.836740
11  1981       Total      Coal  3016.997098
12  1982       Total      Coal  2894.453933
13  1983       Total      Coal  3009.112576
14  1984       Total      Coal  3225.430596
15  1985       Total      Coal  3326.168963
16  1986       Total      Coal  3272.427202
17  1987       Total      Coal  3406.837920
18  1988       Total      Coal  3584.902972
19  1989       Total      Coal  3617.355257
20  1990       Total      Coal  3638.854087
21  1991       Total      Coal  3610.042113
22  1992       Total      Coal  3635.494141

In [91]:
from pmdarima import auto_arima
from sklearn.metrics import mean_squared_error
import numpy as np

In [92]:
# Function to fit ARIMA model and make predictions
def fit_arima(df, test_index, next_count):
    # Convert the DataFrame to a time series with 'year' as the index
    ts = df.set_index('year')['value']

    # Split the data into training and testing sets
    train_data = ts[:test_index]  # Use all data except the last x years for training
    test_data = ts[test_index:]   # Use the last x years for testing
    
    # Use AutoARIMA to automatically select the optimal parameters
    model = auto_arima(train_data, seasonal=False, suppress_warnings=True)

    # Get the final model summary which includes the chosen parameters (p, d, q)
    model_summary = model.summary()
    
    # Print the model summary to see the selected parameters
    print(model_summary)
    
    # Fit the ARIMA model to the training data
    fitted_model = model.fit(train_data)
    
    # Make predictions for the next 13 years
    predictions = fitted_model.predict(n_periods=next_count)
    
    return predictions

In [93]:
# Function to calculate RMSE
def calculate_rmse(actual, predicted):
    return np.sqrt(mean_squared_error(actual, predicted))

# Function to calculate MAPE
def calculate_mape(actual, predicted):
    actual = actual.reset_index(drop = True)
    predicted = predicted.reset_index(drop = True)
    return np.mean(np.abs((actual - predicted) / actual)) * 100

In [95]:
# Dictionary to store predictions, MAPE, and RMSE for each combination of 'sector-name' and 'fuel-name'
all_results = {}

# Iterate over each combination of 'sector-name' and 'fuel-name'
for name, df_group in dfs.items():
    print("Modeling for", name)

    # Calculate the index to split the DataFrame
    split_index = int(len(df_group) * 0.75)

    print("Split at", split_index)

    # Calculate the next data steps to be predicted
    next_count = int(len(df_group) - split_index)

    print("Next count", next_count)
    
    # Fit ARIMA model and make predictions
    predictions = fit_arima(df_group, split_index, next_count)

    actual_values = df_group.set_index('year')['value'][-next_count:]  # Actual values for the last x years

    #print(type(actual_values))
    #print(type(predictions))
    
    # Calculate MAPE
    mape = calculate_mape(actual_values, predictions)
    
    # Calculate RMSE
    rmse = calculate_rmse(actual_values, predictions)
    
    # Store predictions, MAPE, and RMSE in the dictionary
    all_results[name] = {'actuals': actual_values, 'predictions': predictions, 'mape': mape, 'rmse': rmse}

    print()
    print()

Modeling for Commercial carbon dioxide emissions
Split at 39
Next count 13
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   39
Model:               SARIMAX(0, 1, 0)   Log Likelihood                -165.948
Date:                Thu, 23 May 2024   AIC                            333.896
Time:                        16:31:46   BIC                            335.534
Sample:                             0   HQIC                           334.479
                                 - 39
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
sigma2       363.6876     92.180      3.945      0.000     183.018     544.357
===================================================================================
Ljung-Box (L1) (Q):                   0.06   Jarque-Bera (JB):                 0.93
Prob(Q):                              0.81   Prob(JB):                         0.63
Heteroskedasticity (H):               1.05   Skew:                            -0.30
Prob(H) (two-sided):                  0.93   Kurtosis:                         2.51
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Modeling for Electric Power carbon dioxide emissions
Split at 39
Next count 13
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   39
Model:               SARIMAX(0, 1, 0)   Log Likelihood                -226.587
Date:                Thu, 23 May 2024   AIC                            457.174
Time:                        16:31:46   BIC                            460.449
Sample:                             0   HQIC                           458.339
                                 - 39
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept     68.3396     16.600      4.117      0.000      35.805     100.874
sigma2      8846.2361   2583.261      3.424      0.001    3783.138    1.39e+04
===================================================================================
Ljung-Box (L1) (Q):                   0.35   Jarque-Bera (JB):                 1.90
Prob(Q):                              0.55   Prob(JB):                         0.39
Heteroskedasticity (H):               0.95   Skew:                            -0.48
Prob(H) (two-sided):                  0.93   Kurtosis:                         2.46
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Modeling for Industrial carbon dioxide emissions
Split at 39
Next count 13
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   39
Model:               SARIMAX(0, 1, 0)   Log Likelihood                -228.950
Date:                Thu, 23 May 2024   AIC                            459.900
Time:                        16:31:46   BIC                            461.537
Sample:                             0   HQIC                           460.482
                                 - 39
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
sigma2      1.002e+04   2081.584      4.812      0.000    5936.070    1.41e+04
===================================================================================
Ljung-Box (L1) (Q):                   0.16   Jarque-Bera (JB):                 1.41
Prob(Q):                              0.69   Prob(JB):                         0.49
Heteroskedasticity (H):               0.12   Skew:                            -0.47
Prob(H) (two-sided):                  0.00   Kurtosis:                         3.12
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Modeling for Residential carbon dioxide emissions
Split at 39
Next count 13
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   39
Model:               SARIMAX(0, 1, 0)   Log Likelihood                -193.832
Date:                Thu, 23 May 2024   AIC                            389.665
Time:                        16:31:47   BIC                            391.302
Sample:                             0   HQIC                           390.247
                                 - 39
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
sigma2      1577.8173    441.056      3.577      0.000     713.364    2442.271
===================================================================================
Ljung-Box (L1) (Q):                   0.01   Jarque-Bera (JB):                 1.89
Prob(Q):                              0.91   Prob(JB):                         0.39
Heteroskedasticity (H):               1.13   Skew:                            -0.32
Prob(H) (two-sided):                  0.82   Kurtosis:                         2.11
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).


Modeling for Transportation carbon dioxide emissions
Split at 39
Next count 13

C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   39
Model:               SARIMAX(1, 1, 0)   Log Likelihood                -218.082
Date:                Thu, 23 May 2024   AIC                            442.165
Time:                        16:31:47   BIC                            447.077
Sample:                             0   HQIC                           443.912
                                 - 39
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept     21.5161     22.057      0.975      0.329     -21.715      64.747
ar.L1          0.3945      0.230      1.712      0.087      -0.057       0.846
sigma2      5641.5815   1205.732      4.679      0.000    3278.390    8004.773
===================================================================================
Ljung-Box (L1) (Q):                   0.06   Jarque-Bera (JB):                35.19
Prob(Q):                              0.80   Prob(JB):                         0.00
Heteroskedasticity (H):               1.62   Skew:                            -1.66
Prob(H) (two-sided):                  0.39   Kurtosis:                         6.34
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).


Modeling for Coal
Split at 39
Next count 13

C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   39
Model:               SARIMAX(2, 1, 2)   Log Likelihood                -221.921
Date:                Thu, 23 May 2024   AIC                            455.841
Time:                        16:31:48   BIC                            465.667
Sample:                             0   HQIC                           459.337
                                 - 39
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept     97.9135     27.128      3.609      0.000      44.743     151.084
ar.L1         -0.0729      0.295     -0.247      0.805      -0.651       0.505
ar.L2         -0.7800      0.229     -3.400      0.001      -1.230      -0.330
ma.L1         -0.1476      0.457     -0.323      0.747      -1.043       0.748
ma.L2          0.5333      0.336      1.585      0.113      -0.126       1.193
sigma2      6810.5397   1847.751      3.686      0.000    3189.015    1.04e+04
===================================================================================
Ljung-Box (L1) (Q):                   0.01   Jarque-Bera (JB):                 0.64
Prob(Q):                              0.91   Prob(JB):                         0.73
Heteroskedasticity (H):               0.94   Skew:                            -0.30
Prob(H) (two-sided):                  0.91   Kurtosis:                         2.81
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).


Modeling for Natural Gas
Split at 39
Next count 13

C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   39
Model:               SARIMAX(0, 1, 0)   Log Likelihood                -220.692
Date:                Thu, 23 May 2024   AIC                            443.385
Time:                        16:31:49   BIC                            445.022
Sample:                             0   HQIC                           443.967
                                 - 39
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
sigma2      6486.5067   1871.890      3.465      0.001    2817.669    1.02e+04
===================================================================================
Ljung-Box (L1) (Q):                   0.17   Jarque-Bera (JB):                 1.56
Prob(Q):                              0.68   Prob(JB):                         0.46
Heteroskedasticity (H):               0.69   Skew:                            -0.39
Prob(H) (two-sided):                  0.51   Kurtosis:                         2.38
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).


Modeling for Petroleum
Split at 39
Next count 13

C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   39
Model:               SARIMAX(0, 1, 2)   Log Likelihood                -242.247
Date:                Thu, 23 May 2024   AIC                            490.495
Time:                        16:31:50   BIC                            495.408
Sample:                             0   HQIC                           492.243
                                 - 39
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ma.L1          0.6460      0.243      2.656      0.008       0.169       1.123
ma.L2          0.2674      0.243      1.100      0.271      -0.209       0.744
sigma2      1.985e+04   4963.889      4.000      0.000    1.01e+04    2.96e+04
===================================================================================
Ljung-Box (L1) (Q):                   0.01   Jarque-Bera (JB):                 0.66
Prob(Q):                              0.94   Prob(JB):                         0.72
Heteroskedasticity (H):               0.48   Skew:                            -0.28
Prob(H) (two-sided):                  0.19   Kurtosis:                         3.34
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\tsa\base\tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

In [96]:
# Print the predictions, MAPE, and RMSE for each combination of 'sector-name' and 'fuel-name'
for name, results in all_results.items():
    print("Results for", name)
    print("Predictions:", results['predictions'])
    print("Actuals:", results['actuals'])
    print("MAPE:", results['mape'])
    print("RMSE:", results['rmse'])
    print()

Results for Commercial carbon dioxide emissions
Predictions: 39    452.828748
40    452.828748
41    452.828748
42    452.828748
43    452.828748
44    452.828748
45    452.828748
46    452.828748
47    452.828748
48    452.828748
49    452.828748
50    452.828748
51    452.828748
dtype: float64
Actuals: year
2009    448.055358
2010    443.079027
2011    445.006413
2012    403.357829
2013    446.903892
2014    469.613644
2015    483.827425
2016    467.921189
2017    471.383518
2018    512.797113
2019    514.730157
2020    471.587607
2021    495.812665
Name: value, dtype: float64
MAPE: 5.548039391498668
RMSE: 32.93784368382742

Results for Electric Power carbon dioxide emissions
Predictions: 39    4788.125205
40    4856.464817
41    4924.804428
42    4993.144039
43    5061.483650
44    5129.823262
45    5198.162873
46    5266.502484
47    5334.842095
48    5403.181707
49    5471.521318
50    5539.860929
51    5608.200540
dtype: float64
Actuals: year
2009    4291.881600
2010    4519.703315
2011    4318.229638
2012    4048.420363
2013    4077.898010
2014    4076.013505
2015    3802.693130
2016    3619.234689
2017    3465.440881
2018    3509.389641
2019    3216.273155
2020    2880.864213
2021    3084.080959
Name: value, dtype: float64
MAPE: 41.59618898597757
RMSE: 1616.4438959422291

Results for Industrial carbon dioxide emissions
Predictions: 39    1933.737484
40    1933.737484
41    1933.737484
42    1933.737484
43    1933.737484
44    1933.737484
45    1933.737484
46    1933.737484
47    1933.737484
48    1933.737484
49    1933.737484
50    1933.737484
51    1933.737484
dtype: float64
Actuals: year
2009    1708.897325
2010    1842.823351
2011    1849.215164
2012    1873.046986
2013    1916.289557
2014    1938.377173
2015    1901.008840
2016    1897.209399
2017    1935.695108
2018    2009.632886
2019    2013.284413
2020    1898.128137
2021    1960.369449
Name: value, dtype: float64
MAPE: 3.212429950682811
RMSE: 81.54574139224553

Results for Residential carbon dioxide emissions
Predictions: 39    716.125792
40    716.125792
41    716.125792
42    716.125792
43    716.125792
44    716.125792
45    716.125792
46    716.125792
47    716.125792
48    716.125792
49    716.125792
50    716.125792
51    716.125792
dtype: float64
Actuals: year
2009    679.144705
2010    673.168838
2011    653.630783
2012    573.591847
2013    666.399636
2014    699.673933
2015    646.485009
2016    599.169065
2017    605.335002
2018    690.452603
2019    695.763574
2020    640.181573
2021    652.485586
Name: value, dtype: float64
MAPE: 10.223551311744304
RMSE: 74.35489386703082

Results for Transportation carbon dioxide emissions
Predictions: 39    3703.677415
40    3693.244799
41    3710.645101
42    3739.025774
43    3771.738315
44    3806.159822
45    3841.255535
46    3876.617228
47    3912.083852
48    3947.591874
49    3983.116227
50    4018.647023
51    4054.180361
dtype: float64
Actuals: year
2009    3663.563918
2010    3691.595412
2011    3633.718334
2012    3560.770465
2013    3614.691326
2014    3650.893114
2015    3700.757759
2016    3776.025765
2017    3809.483170
2018    3868.898393
2019    3879.401066
2020    3298.672725
2021    3629.705992
Name: value, dtype: float64
MAPE: 4.941698711139172
RMSE: 254.79284940269042

Results for Coal
Predictions: 39    4332.447153
40    4391.682643
41    4435.122481
42    4483.663990
43    4544.154519
44    4599.794477
45    4646.467568
46    4697.577949
47    4755.359183
48    4809.192887
49    4858.110975
50    4910.466601
51    4966.405901
dtype: float64
Actuals: year
2009    3756.028591
2010    3972.695120
2011    3750.400971
2012    3315.753311
2013    3440.059630
2014    3431.628172
2015    2968.063701
2016    2715.282356
2017    2642.989821
2018    2531.149755
2019    2160.215370
2020    1755.849253
2021    2017.214715
Name: value, dtype: float64
MAPE: 68.90325214692847
RMSE: 1906.474918682826

Results for Natural Gas
Predictions: 39    2502.234159
40    2502.234159
41    2502.234159
42    2502.234159
43    2502.234159
44    2502.234159
45    2502.234159
46    2502.234159
47    2502.234159
48    2502.234159
49    2502.234159
50    2502.234159
51    2502.234159
dtype: float64
Actuals: year
2009    2458.503330
2010    2580.564588
2011    2620.021498
2012    2733.762409
2013    2805.410158
2014    2864.938273
2015    2945.986636
2016    2967.567874
2017    2931.829023
2018    3258.258351
2019    3370.235498
2020    3300.450490
2021    3309.710671
Name: value, dtype: float64
MAPE: 14.167912490031814
RMSE: 519.7016300952545

Results for Petroleum
Predictions: 39    4625.565362
40    4536.634842
41    4536.634842
42    4536.634842
43    4536.634842
44    4536.634842
45    4536.634842
46    4536.634842
47    4536.634842
48    4536.634842
49    4536.634842
50    4536.634842
51    4536.634842
dtype: float64
Actuals: year
2009    4577.010985
2010    4617.110235
2011    4529.377863
2012    4409.671770
2013    4476.712633
2014    4538.004924
2015    4620.721826
2016    4676.709877
2017    4712.518835
2018    4801.762530
2019    4789.001497
2020    4133.134512
2021    4495.529265
Name: value, dtype: float64
MAPE: 2.863637314084973
RMSE: 172.02622107109104

In [137]:
# Creating Empty DataFrame and Storing it in variable df
processed_df =  pd.DataFrame()

processed_df.insert(0, 'year', range(1970, 2021 + 1))
 
# Printing Empty DataFrame
print(processed_df)

    year
0   1970
1   1971
2   1972
3   1973
4   1974
5   1975
6   1976
7   1977
8   1978
9   1979
10  1980
11  1981
12  1982
13  1983
14  1984
15  1985
16  1986
17  1987
18  1988
19  1989
20  1990
21  1991
22  1992
23  1993
24  1994
25  1995
26  1996
27  1997
28  1998
29  1999
30  2000
31  2001
32  2002
33  2003
34  2004
35  2005
36  2006
37  2007
38  2008
39  2009
40  2010
41  2011
42  2012
43  2013
44  2014
45  2015
46  2016
47  2017
48  2018
49  2019
50  2020
51  2021

In [138]:
# Insert Actual Data into Dataframe
# Iterate over each combination of 'sector-name' and 'fuel-name'
for name, df_group in dfs.items():
    print("Adding Column for", name)

    processed_df.insert(0, name + " Actual", df_group['value'])

# Printing Empty DataFrame
print(processed_df)

Adding Column for Commercial carbon dioxide emissions
Adding Column for Electric Power carbon dioxide emissions
Adding Column for Industrial carbon dioxide emissions
Adding Column for Residential carbon dioxide emissions
Adding Column for Transportation carbon dioxide emissions
Adding Column for Coal
Adding Column for Natural Gas
Adding Column for Petroleum
    Petroleum Actual  Natural Gas Actual  Coal Actual  \
0        3939.954943         2255.982068  2311.126560
1        4083.996663         2325.650502  2187.743724
2        4394.679931         2359.147560  2283.000112
3        4639.629455         2347.243536  2443.490583
4        4444.107084         2257.439848  2386.105741
5        4373.147918         2078.381797  2388.027333
6        4694.591088         2120.151965  2563.195745
7        4949.963919         2077.356991  2627.566307
8        5046.829520         2087.829825  2602.873837
9        4856.389913         2153.663515  2843.300211
10       4458.481488         2122.277028  2924.836740
11       4169.411750         2074.575749  3016.997098
12       3952.016678         1930.018853  2894.453933
13       3934.166483         1807.680903  3009.112576
14       4048.372722         1927.212791  3225.430596
15       4024.826595         1858.967229  3326.168963
16       4201.468826         1741.496678  3272.427202
17       4262.027423         1847.916075  3406.837920
18       4456.839524         1932.385636  3584.902972
19       4455.422232         2052.654898  3617.355257
20       4352.492348         2054.802853  3638.854087
21       4239.840342         2094.725712  3610.042113
22       4326.088023         2166.783643  3635.494141
23       4351.014705         2224.159334  3758.272863
24       4436.045860         2276.170175  3770.835057
25       4421.566557         2377.655807  3813.294965
26       4602.161540         2421.771807  3984.510120
27       4642.240075         2444.038137  4067.450536
28       4734.866336         2392.811083  4098.322338
29       4853.895152         2397.608075  4102.382660
30       4948.637024         2490.053565  4293.881862
31       4970.284459         2375.661077  4167.281271
32       4958.144778         2459.132773  4172.197235
33       5085.822591         2388.256857  4257.868684
34       5239.596664         2404.553176  4285.010742
35       5260.229302         2368.844072  4350.835494
36       5199.486165         2336.113530  4278.512602
37       5171.248433         2487.102307  4336.251597
38       4836.756446         2502.234159  4268.147608
39       4577.010985         2458.503330  3756.028591
40       4617.110235         2580.564588  3972.695120
41       4529.377863         2620.021498  3750.400971
42       4409.671770         2733.762409  3315.753311
43       4476.712633         2805.410158  3440.059630
44       4538.004924         2864.938273  3431.628172
45       4620.721826         2945.986636  2968.063701
46       4676.709877         2967.567874  2715.282356
47       4712.518835         2931.829023  2642.989821
48       4801.762530         3258.258351  2531.149755
49       4789.001497         3370.235498  2160.215370
50       4133.134512         3300.450490  1755.849253
51       4495.529265         3309.710671  2017.214715

    Transportation carbon dioxide emissions Actual  \
0                                      2263.336813
1                                      2352.662168
2                                      2492.989811
3                                      2624.260159
4                                      2556.368151
5                                      2577.130243
6                                      2700.961919
7                                      2805.805592
8                                      2920.220529
9                                      2899.750450
10                                     2789.706724
11                                     2761.261172
12                                     2698.007231
13                                     2707.416975
14                                     2770.797704
15                                     2833.080796
16                                     2932.293175
17                                     3024.922701
18                                     3143.865763
19                                     3165.742537
20                                     3158.617365
21                                     3114.038523
22                                     3153.668515
23                                     3194.926637
24                                     3280.664965
25                                     3351.855474
26                                     3451.104988
27                                     3491.039804
28                                     3564.888343
29                                     3657.169779
30                                     3768.910461
31                                     3711.563437
32                                     3790.961793
33                                     3825.198300
34                                     3934.943640
35                                     3976.275391
36                                     4039.056250
37                                     4044.474542
38                                     3784.660595
39                                     3663.563918
40                                     3691.595412
41                                     3633.718334
42                                     3560.770465
43                                     3614.691326
44                                     3650.893114
45                                     3700.757759
46                                     3776.025765
47                                     3809.483170
48                                     3868.898393
49                                     3879.401066
50                                     3298.672725
51                                     3629.705992

    Residential carbon dioxide emissions Actual  \
0                                    955.538394
1                                    966.514498
2                                    990.067779
3                                    949.582197
4                                    900.987199
5                                    899.900507
6                                    945.132872
7                                    917.072452
8                                    912.628744
9                                    845.760394
10                                   770.299655
11                                   718.852439
12                                   715.432611
13                                   677.145313
14                                   724.429863
15                                   715.998096
16                                   698.703342
17                                   709.064810
18                                   751.579967
19                                   765.263420
20                                   683.523662
21                                   697.021138
22                                   716.624591
23                                   749.638885
24                                   731.805734
25                                   726.452501
26                                   784.007227
27                                   746.946421
28                                   680.643334
29                                   722.475387
30                                   762.502542
31                                   737.476855
32                                   738.160919
33                                   774.233858
34                                   746.804376
35                                   731.594446
36                                   648.144233
37                                   690.041710
38                                   716.125792
39                                   679.144705
40                                   673.168838
41                                   653.630783
42                                   573.591847
43                                   666.399636
44                                   699.673933
45                                   646.485009
46                                   599.169065
47                                   605.335002
48                                   690.452603
49                                   695.763574
50                                   640.181573
51                                   652.485586

    Industrial carbon dioxide emissions Actual  \
0                                  2640.355565
1                                  2546.852979
2                                  2627.657723
3                                  2741.921674
4                                  2607.819091
5                                  2379.670547
6                                  2492.945751
7                                  2526.793507
8                                  2480.167923
9                                  2561.244604
10                                 2336.933663
11                                 2187.065039
12                                 1924.193036
13                                 1841.574906
14                                 2028.458639
15                                 1937.573639
16                                 1889.569717
17                                 1952.958580
18                                 2057.823180
19                                 2059.939625
20                                 2108.518608
21                                 2042.128966
22                                 2137.969344
23                                 2121.887519
24                                 2150.403357
25                                 2173.382704
26                                 2249.772298
27                                 2257.225950
28                                 2177.607696
29                                 2141.364189
30                                 2128.362129
31                                 2085.384810
32                                 2051.148026
33                                 2039.867739
34                                 2099.981090
35                                 2014.756219
36                                 2020.428078
37                                 2002.537159
38                                 1933.737484
39                                 1708.897325
40                                 1842.823351
41                                 1849.215164
42                                 1873.046986
43                                 1916.289557
44                                 1938.377173
45                                 1901.008840
46                                 1897.209399
47                                 1935.695108
48                                 2009.632886
49                                 2013.284413
50                                 1898.128137
51                                 1960.369449

    Electric Power carbon dioxide emissions Actual  \
0                                      2122.880366
1                                      2197.656773
2                                      2383.076058
3                                      2566.447440
4                                      2498.006026
5                                      2487.013548
6                                      2703.611561
7                                      2879.498190
8                                      2894.706729
9                                      3016.604041
10                                     3109.892693
11                                     3129.793197
12                                     2973.778117
13                                     3057.463269
14                                     3190.157626
15                                     3273.440794
16                                     3246.229950
17                                     3375.460409
18                                     3544.337740
19                                     3664.005759
20                                     3641.405941
21                                     3635.915536
22                                     3662.271396
23                                     3813.542926
24                                     3862.160757
25                                     3896.292227
26                                     4041.422063
27                                     4176.092507
28                                     4354.256748
29                                     4379.981421
30                                     4593.604268
31                                     4518.119350
32                                     4545.787928
33                                     4608.072577
34                                     4669.995246
35                                     4801.693850
36                                     4690.095878
37                                     4822.661217
38                                     4719.785594
39                                     4291.881600
40                                     4519.703315
41                                     4318.229638
42                                     4048.420363
43                                     4077.898010
44                                     4076.013505
45                                     3802.693130
46                                     3619.234689
47                                     3465.440881
48                                     3509.389641
49                                     3216.273155
50                                     2880.864213
51                                     3084.080959

    Commercial carbon dioxide emissions Actual  year
0                                   524.952433  1970
1                                   533.704471  1971
2                                   543.036232  1972
3                                   548.152104  1973
4                                   524.472206  1974
5                                   495.842203  1975
6                                   535.286695  1976
7                                   525.717476  1977
8                                   529.809257  1978
9                                   529.994150  1979
10                                  498.762521  1980
11                                  464.012750  1981
12                                  465.078469  1982
13                                  467.359499  1983
14                                  487.172277  1984
15                                  449.869462  1985
16                                  448.596522  1986
17                                  454.374918  1987
18                                  476.521482  1988
19                                  470.481046  1989
20                                  454.083712  1990
21                                  455.504004  1991
22                                  457.831961  1992
23                                  453.450935  1993
24                                  458.016279  1994
25                                  464.534423  1995
26                                  482.136891  1996
27                                  482.424066  1997
28                                  448.603636  1998
29                                  452.895111  1999
30                                  479.193051  2000
31                                  460.682355  2001
32                                  463.416120  2002
33                                  484.575658  2003
34                                  477.436230  2004
35                                  455.588962  2005
36                                  416.387858  2006
37                                  434.887709  2007
38                                  452.828748  2008
39                                  448.055358  2009
40                                  443.079027  2010
41                                  445.006413  2011
42                                  403.357829  2012
43                                  446.903892  2013
44                                  469.613644  2014
45                                  483.827425  2015
46                                  467.921189  2016
47                                  471.383518  2017
48                                  512.797113  2018
49                                  514.730157  2019
50                                  471.587607  2020
51                                  495.812665  2021

In [139]:
# Insert Placeholder Data for Predicted Data into Dataframe
# Iterate over each combination of 'sector-name' and 'fuel-name'
for name, df_group in dfs.items():
    print("Adding Column for", name)

    processed_df.insert(0, name, df_group['value'])

# Printing Empty DataFrame
print(processed_df)

Adding Column for Commercial carbon dioxide emissions
Adding Column for Electric Power carbon dioxide emissions
Adding Column for Industrial carbon dioxide emissions
Adding Column for Residential carbon dioxide emissions
Adding Column for Transportation carbon dioxide emissions
Adding Column for Coal
Adding Column for Natural Gas
Adding Column for Petroleum
      Petroleum  Natural Gas         Coal  \
0   3939.954943  2255.982068  2311.126560
1   4083.996663  2325.650502  2187.743724
2   4394.679931  2359.147560  2283.000112
3   4639.629455  2347.243536  2443.490583
4   4444.107084  2257.439848  2386.105741
5   4373.147918  2078.381797  2388.027333
6   4694.591088  2120.151965  2563.195745
7   4949.963919  2077.356991  2627.566307
8   5046.829520  2087.829825  2602.873837
9   4856.389913  2153.663515  2843.300211
10  4458.481488  2122.277028  2924.836740
11  4169.411750  2074.575749  3016.997098
12  3952.016678  1930.018853  2894.453933
13  3934.166483  1807.680903  3009.112576
14  4048.372722  1927.212791  3225.430596
15  4024.826595  1858.967229  3326.168963
16  4201.468826  1741.496678  3272.427202
17  4262.027423  1847.916075  3406.837920
18  4456.839524  1932.385636  3584.902972
19  4455.422232  2052.654898  3617.355257
20  4352.492348  2054.802853  3638.854087
21  4239.840342  2094.725712  3610.042113
22  4326.088023  2166.783643  3635.494141
23  4351.014705  2224.159334  3758.272863
24  4436.045860  2276.170175  3770.835057
25  4421.566557  2377.655807  3813.294965
26  4602.161540  2421.771807  3984.510120
27  4642.240075  2444.038137  4067.450536
28  4734.866336  2392.811083  4098.322338
29  4853.895152  2397.608075  4102.382660
30  4948.637024  2490.053565  4293.881862
31  4970.284459  2375.661077  4167.281271
32  4958.144778  2459.132773  4172.197235
33  5085.822591  2388.256857  4257.868684
34  5239.596664  2404.553176  4285.010742
35  5260.229302  2368.844072  4350.835494
36  5199.486165  2336.113530  4278.512602
37  5171.248433  2487.102307  4336.251597
38  4836.756446  2502.234159  4268.147608
39  4577.010985  2458.503330  3756.028591
40  4617.110235  2580.564588  3972.695120
41  4529.377863  2620.021498  3750.400971
42  4409.671770  2733.762409  3315.753311
43  4476.712633  2805.410158  3440.059630
44  4538.004924  2864.938273  3431.628172
45  4620.721826  2945.986636  2968.063701
46  4676.709877  2967.567874  2715.282356
47  4712.518835  2931.829023  2642.989821
48  4801.762530  3258.258351  2531.149755
49  4789.001497  3370.235498  2160.215370
50  4133.134512  3300.450490  1755.849253
51  4495.529265  3309.710671  2017.214715

    Transportation carbon dioxide emissions  \
0                               2263.336813
1                               2352.662168
2                               2492.989811
3                               2624.260159
4                               2556.368151
5                               2577.130243
6                               2700.961919
7                               2805.805592
8                               2920.220529
9                               2899.750450
10                              2789.706724
11                              2761.261172
12                              2698.007231
13                              2707.416975
14                              2770.797704
15                              2833.080796
16                              2932.293175
17                              3024.922701
18                              3143.865763
19                              3165.742537
20                              3158.617365
21                              3114.038523
22                              3153.668515
23                              3194.926637
24                              3280.664965
25                              3351.855474
26                              3451.104988
27                              3491.039804
28                              3564.888343
29                              3657.169779
30                              3768.910461
31                              3711.563437
32                              3790.961793
33                              3825.198300
34                              3934.943640
35                              3976.275391
36                              4039.056250
37                              4044.474542
38                              3784.660595
39                              3663.563918
40                              3691.595412
41                              3633.718334
42                              3560.770465
43                              3614.691326
44                              3650.893114
45                              3700.757759
46                              3776.025765
47                              3809.483170
48                              3868.898393
49                              3879.401066
50                              3298.672725
51                              3629.705992

    Residential carbon dioxide emissions  Industrial carbon dioxide emissions  \
0                             955.538394                          2640.355565
1                             966.514498                          2546.852979
2                             990.067779                          2627.657723
3                             949.582197                          2741.921674
4                             900.987199                          2607.819091
5                             899.900507                          2379.670547
6                             945.132872                          2492.945751
7                             917.072452                          2526.793507
8                             912.628744                          2480.167923
9                             845.760394                          2561.244604
10                            770.299655                          2336.933663
11                            718.852439                          2187.065039
12                            715.432611                          1924.193036
13                            677.145313                          1841.574906
14                            724.429863                          2028.458639
15                            715.998096                          1937.573639
16                            698.703342                          1889.569717
17                            709.064810                          1952.958580
18                            751.579967                          2057.823180
19                            765.263420                          2059.939625
20                            683.523662                          2108.518608
21                            697.021138                          2042.128966
22                            716.624591                          2137.969344
23                            749.638885                          2121.887519
24                            731.805734                          2150.403357
25                            726.452501                          2173.382704
26                            784.007227                          2249.772298
27                            746.946421                          2257.225950
28                            680.643334                          2177.607696
29                            722.475387                          2141.364189
30                            762.502542                          2128.362129
31                            737.476855                          2085.384810
32                            738.160919                          2051.148026
33                            774.233858                          2039.867739
34                            746.804376                          2099.981090
35                            731.594446                          2014.756219
36                            648.144233                          2020.428078
37                            690.041710                          2002.537159
38                            716.125792                          1933.737484
39                            679.144705                          1708.897325
40                            673.168838                          1842.823351
41                            653.630783                          1849.215164
42                            573.591847                          1873.046986
43                            666.399636                          1916.289557
44                            699.673933                          1938.377173
45                            646.485009                          1901.008840
46                            599.169065                          1897.209399
47                            605.335002                          1935.695108
48                            690.452603                          2009.632886
49                            695.763574                          2013.284413
50                            640.181573                          1898.128137
51                            652.485586                          1960.369449

    Electric Power carbon dioxide emissions  \
0                               2122.880366
1                               2197.656773
2                               2383.076058
3                               2566.447440
4                               2498.006026
5                               2487.013548
6                               2703.611561
7                               2879.498190
8                               2894.706729
9                               3016.604041
10                              3109.892693
11                              3129.793197
12                              2973.778117
13                              3057.463269
14                              3190.157626
15                              3273.440794
16                              3246.229950
17                              3375.460409
18                              3544.337740
19                              3664.005759
20                              3641.405941
21                              3635.915536
22                              3662.271396
23                              3813.542926
24                              3862.160757
25                              3896.292227
26                              4041.422063
27                              4176.092507
28                              4354.256748
29                              4379.981421
30                              4593.604268
31                              4518.119350
32                              4545.787928
33                              4608.072577
34                              4669.995246
35                              4801.693850
36                              4690.095878
37                              4822.661217
38                              4719.785594
39                              4291.881600
40                              4519.703315
41                              4318.229638
42                              4048.420363
43                              4077.898010
44                              4076.013505
45                              3802.693130
46                              3619.234689
47                              3465.440881
48                              3509.389641
49                              3216.273155
50                              2880.864213
51                              3084.080959

    Commercial carbon dioxide emissions  Petroleum Actual  Natural Gas Actual  \
0                            524.952433       3939.954943         2255.982068
1                            533.704471       4083.996663         2325.650502
2                            543.036232       4394.679931         2359.147560
3                            548.152104       4639.629455         2347.243536
4                            524.472206       4444.107084         2257.439848
5                            495.842203       4373.147918         2078.381797
6                            535.286695       4694.591088         2120.151965
7                            525.717476       4949.963919         2077.356991
8                            529.809257       5046.829520         2087.829825
9                            529.994150       4856.389913         2153.663515
10                           498.762521       4458.481488         2122.277028
11                           464.012750       4169.411750         2074.575749
12                           465.078469       3952.016678         1930.018853
13                           467.359499       3934.166483         1807.680903
14                           487.172277       4048.372722         1927.212791
15                           449.869462       4024.826595         1858.967229
16                           448.596522       4201.468826         1741.496678
17                           454.374918       4262.027423         1847.916075
18                           476.521482       4456.839524         1932.385636
19                           470.481046       4455.422232         2052.654898
20                           454.083712       4352.492348         2054.802853
21                           455.504004       4239.840342         2094.725712
22                           457.831961       4326.088023         2166.783643
23                           453.450935       4351.014705         2224.159334
24                           458.016279       4436.045860         2276.170175
25                           464.534423       4421.566557         2377.655807
26                           482.136891       4602.161540         2421.771807
27                           482.424066       4642.240075         2444.038137
28                           448.603636       4734.866336         2392.811083
29                           452.895111       4853.895152         2397.608075
30                           479.193051       4948.637024         2490.053565
31                           460.682355       4970.284459         2375.661077
32                           463.416120       4958.144778         2459.132773
33                           484.575658       5085.822591         2388.256857
34                           477.436230       5239.596664         2404.553176
35                           455.588962       5260.229302         2368.844072
36                           416.387858       5199.486165         2336.113530
37                           434.887709       5171.248433         2487.102307
38                           452.828748       4836.756446         2502.234159
39                           448.055358       4577.010985         2458.503330
40                           443.079027       4617.110235         2580.564588
41                           445.006413       4529.377863         2620.021498
42                           403.357829       4409.671770         2733.762409
43                           446.903892       4476.712633         2805.410158
44                           469.613644       4538.004924         2864.938273
45                           483.827425       4620.721826         2945.986636
46                           467.921189       4676.709877         2967.567874
47                           471.383518       4712.518835         2931.829023
48                           512.797113       4801.762530         3258.258351
49                           514.730157       4789.001497         3370.235498
50                           471.587607       4133.134512         3300.450490
51                           495.812665       4495.529265         3309.710671

    Coal Actual  Transportation carbon dioxide emissions Actual  \
0   2311.126560                                     2263.336813
1   2187.743724                                     2352.662168
2   2283.000112                                     2492.989811
3   2443.490583                                     2624.260159
4   2386.105741                                     2556.368151
5   2388.027333                                     2577.130243
6   2563.195745                                     2700.961919
7   2627.566307                                     2805.805592
8   2602.873837                                     2920.220529
9   2843.300211                                     2899.750450
10  2924.836740                                     2789.706724
11  3016.997098                                     2761.261172
12  2894.453933                                     2698.007231
13  3009.112576                                     2707.416975
14  3225.430596                                     2770.797704
15  3326.168963                                     2833.080796
16  3272.427202                                     2932.293175
17  3406.837920                                     3024.922701
18  3584.902972                                     3143.865763
19  3617.355257                                     3165.742537
20  3638.854087                                     3158.617365
21  3610.042113                                     3114.038523
22  3635.494141                                     3153.668515
23  3758.272863                                     3194.926637
24  3770.835057                                     3280.664965
25  3813.294965                                     3351.855474
26  3984.510120                                     3451.104988
27  4067.450536                                     3491.039804
28  4098.322338                                     3564.888343
29  4102.382660                                     3657.169779
30  4293.881862                                     3768.910461
31  4167.281271                                     3711.563437
32  4172.197235                                     3790.961793
33  4257.868684                                     3825.198300
34  4285.010742                                     3934.943640
35  4350.835494                                     3976.275391
36  4278.512602                                     4039.056250
37  4336.251597                                     4044.474542
38  4268.147608                                     3784.660595
39  3756.028591                                     3663.563918
40  3972.695120                                     3691.595412
41  3750.400971                                     3633.718334
42  3315.753311                                     3560.770465
43  3440.059630                                     3614.691326
44  3431.628172                                     3650.893114
45  2968.063701                                     3700.757759
46  2715.282356                                     3776.025765
47  2642.989821                                     3809.483170
48  2531.149755                                     3868.898393
49  2160.215370                                     3879.401066
50  1755.849253                                     3298.672725
51  2017.214715                                     3629.705992

    Residential carbon dioxide emissions Actual  \
0                                    955.538394
1                                    966.514498
2                                    990.067779
3                                    949.582197
4                                    900.987199
5                                    899.900507
6                                    945.132872
7                                    917.072452
8                                    912.628744
9                                    845.760394
10                                   770.299655
11                                   718.852439
12                                   715.432611
13                                   677.145313
14                                   724.429863
15                                   715.998096
16                                   698.703342
17                                   709.064810
18                                   751.579967
19                                   765.263420
20                                   683.523662

In [ ]:
for name, results in all_results.items():
    print("Results for", name)
    print("Predictions:", results['predictions'])
    print(type(results['predictions']))
    for i in range(len(results['predictions'])):
        print(results['predictions'].reset_index(drop = True).iloc[-i])

In [140]:
for name, results in all_results.items():
    print("Puncturing Predicted Values for", name)
    for i in range(len(results['predictions'])):
        j = i + 1
        processed_df.at[processed_df.shape[0]-j,name] = results['predictions'].reset_index(drop = True).iloc[-j]

# Printing Empty DataFrame
print(processed_df)

Puncturing Predicted Values for Commercial carbon dioxide emissions
Puncturing Predicted Values for Electric Power carbon dioxide emissions
Puncturing Predicted Values for Industrial carbon dioxide emissions
Puncturing Predicted Values for Residential carbon dioxide emissions
Puncturing Predicted Values for Transportation carbon dioxide emissions
Puncturing Predicted Values for Coal
Puncturing Predicted Values for Natural Gas
Puncturing Predicted Values for Petroleum
      Petroleum  Natural Gas         Coal  \
0   3939.954943  2255.982068  2311.126560
1   4083.996663  2325.650502  2187.743724
2   4394.679931  2359.147560  2283.000112
3   4639.629455  2347.243536  2443.490583
4   4444.107084  2257.439848  2386.105741
5   4373.147918  2078.381797  2388.027333
6   4694.591088  2120.151965  2563.195745
7   4949.963919  2077.356991  2627.566307
8   5046.829520  2087.829825  2602.873837
9   4856.389913  2153.663515  2843.300211
10  4458.481488  2122.277028  2924.836740
11  4169.411750  2074.575749  3016.997098
12  3952.016678  1930.018853  2894.453933
13  3934.166483  1807.680903  3009.112576
14  4048.372722  1927.212791  3225.430596
15  4024.826595  1858.967229  3326.168963
16  4201.468826  1741.496678  3272.427202
17  4262.027423  1847.916075  3406.837920
18  4456.839524  1932.385636  3584.902972
19  4455.422232  2052.654898  3617.355257
20  4352.492348  2054.802853  3638.854087
21  4239.840342  2094.725712  3610.042113
22  4326.088023  2166.783643  3635.494141
23  4351.014705  2224.159334  3758.272863
24  4436.045860  2276.170175  3770.835057
25  4421.566557  2377.655807  3813.294965
26  4602.161540  2421.771807  3984.510120
27  4642.240075  2444.038137  4067.450536
28  4734.866336  2392.811083  4098.322338
29  4853.895152  2397.608075  4102.382660
30  4948.637024  2490.053565  4293.881862
31  4970.284459  2375.661077  4167.281271
32  4958.144778  2459.132773  4172.197235
33  5085.822591  2388.256857  4257.868684
34  5239.596664  2404.553176  4285.010742
35  5260.229302  2368.844072  4350.835494
36  5199.486165  2336.113530  4278.512602
37  5171.248433  2487.102307  4336.251597
38  4836.756446  2502.234159  4268.147608
39  4625.565362  2502.234159  4332.447153
40  4536.634842  2502.234159  4391.682643
41  4536.634842  2502.234159  4435.122481
42  4536.634842  2502.234159  4483.663990
43  4536.634842  2502.234159  4544.154519
44  4536.634842  2502.234159  4599.794477
45  4536.634842  2502.234159  4646.467568
46  4536.634842  2502.234159  4697.577949
47  4536.634842  2502.234159  4755.359183
48  4536.634842  2502.234159  4809.192887
49  4536.634842  2502.234159  4858.110975
50  4536.634842  2502.234159  4910.466601
51  4536.634842  2502.234159  4966.405901

    Transportation carbon dioxide emissions  \
0                               2263.336813
1                               2352.662168
2                               2492.989811
3                               2624.260159
4                               2556.368151
5                               2577.130243
6                               2700.961919
7                               2805.805592
8                               2920.220529
9                               2899.750450
10                              2789.706724
11                              2761.261172
12                              2698.007231
13                              2707.416975
14                              2770.797704
15                              2833.080796
16                              2932.293175
17                              3024.922701
18                              3143.865763
19                              3165.742537
20                              3158.617365
21                              3114.038523
22                              3153.668515
23                              3194.926637
24                              3280.664965
25                              3351.855474
26                              3451.104988
27                              3491.039804
28                              3564.888343
29                              3657.169779
30                              3768.910461
31                              3711.563437
32                              3790.961793
33                              3825.198300
34                              3934.943640
35                              3976.275391
36                              4039.056250
37                              4044.474542
38                              3784.660595
39                              3703.677415
40                              3693.244799
41                              3710.645101
42                              3739.025774
43                              3771.738315
44                              3806.159822
45                              3841.255535
46                              3876.617228
47                              3912.083852
48                              3947.591874
49                              3983.116227
50                              4018.647023
51                              4054.180361

    Residential carbon dioxide emissions  Industrial carbon dioxide emissions  \
0                             955.538394                          2640.355565
1                             966.514498                          2546.852979
2                             990.067779                          2627.657723
3                             949.582197                          2741.921674
4                             900.987199                          2607.819091
5                             899.900507                          2379.670547
6                             945.132872                          2492.945751
7                             917.072452                          2526.793507
8                             912.628744                          2480.167923
9                             845.760394                          2561.244604
10                            770.299655                          2336.933663
11                            718.852439                          2187.065039
12                            715.432611                          1924.193036
13                            677.145313                          1841.574906
14                            724.429863                          2028.458639
15                            715.998096                          1937.573639
16                            698.703342                          1889.569717
17                            709.064810                          1952.958580
18                            751.579967                          2057.823180
19                            765.263420                          2059.939625
20                            683.523662                          2108.518608
21                            697.021138                          2042.128966
22                            716.624591                          2137.969344
23                            749.638885                          2121.887519
24                            731.805734                          2150.403357
25                            726.452501                          2173.382704
26                            784.007227                          2249.772298
27                            746.946421                          2257.225950
28                            680.643334                          2177.607696
29                            722.475387                          2141.364189
30                            762.502542                          2128.362129
31                            737.476855                          2085.384810
32                            738.160919                          2051.148026
33                            774.233858                          2039.867739
34                            746.804376                          2099.981090
35                            731.594446                          2014.756219
36                            648.144233                          2020.428078
37                            690.041710                          2002.537159
38                            716.125792                          1933.737484
39                            716.125792                          1933.737484
40                            716.125792                          1933.737484
41                            716.125792                          1933.737484
42                            716.125792                          1933.737484
43                            716.125792                          1933.737484
44                            716.125792                          1933.737484
45                            716.125792                          1933.737484
46                            716.125792                          1933.737484
47                            716.125792                          1933.737484
48                            716.125792                          1933.737484
49                            716.125792                          1933.737484
50                            716.125792                          1933.737484
51                            716.125792                          1933.737484

    Electric Power carbon dioxide emissions  \
0                               2122.880366
1                               2197.656773
2                               2383.076058
3                               2566.447440
4                               2498.006026
5                               2487.013548
6                               2703.611561
7                               2879.498190
8                               2894.706729
9                               3016.604041
10                              3109.892693
11                              3129.793197
12                              2973.778117
13                              3057.463269
14                              3190.157626
15                              3273.440794
16                              3246.229950
17                              3375.460409
18                              3544.337740
19                              3664.005759
20                              3641.405941
21                              3635.915536
22                              3662.271396
23                              3813.542926
24                              3862.160757
25                              3896.292227
26                              4041.422063
27                              4176.092507
28                              4354.256748
29                              4379.981421
30                              4593.604268
31                              4518.119350
32                              4545.787928
33                              4608.072577
34                              4669.995246
35                              4801.693850
36                              4690.095878
37                              4822.661217
38                              4719.785594
39                              4788.125205
40                              4856.464817
41                              4924.804428
42                              4993.144039
43                              5061.483650
44                              5129.823262
45                              5198.162873
46                              5266.502484
47                              5334.842095
48                              5403.181707
49                              5471.521318
50                              5539.860929
51                              5608.200540

    Commercial carbon dioxide emissions  Petroleum Actual  Natural Gas Actual  \
0                            524.952433       3939.954943         2255.982068
1                            533.704471       4083.996663         2325.650502
2                            543.036232       4394.679931         2359.147560
3                            548.152104       4639.629455         2347.243536
4                            524.472206       4444.107084         2257.439848
5                            495.842203       4373.147918         2078.381797
6                            535.286695       4694.591088         2120.151965
7                            525.717476       4949.963919         2077.356991
8                            529.809257       5046.829520         2087.829825
9                            529.994150       4856.389913         2153.663515
10                           498.762521       4458.481488         2122.277028
11                           464.012750       4169.411750         2074.575749
12                           465.078469       3952.016678         1930.018853
13                           467.359499       3934.166483         1807.680903
14                           487.172277       4048.372722         1927.212791
15                           449.869462       4024.826595         1858.967229
16                           448.596522       4201.468826         1741.496678
17                           454.374918       4262.027423         1847.916075
18                           476.521482       4456.839524         1932.385636
19                           470.481046       4455.422232         2052.654898
20                           454.083712       4352.492348         2054.802853
21                           455.504004       4239.840342         2094.725712
22                           457.831961       4326.088023         2166.783643
23                           453.450935       4351.014705         2224.159334
24                           458.016279       4436.045860         2276.170175
25                           464.534423       4421.566557         2377.655807
26                           482.136891       4602.161540         2421.771807
27                           482.424066       4642.240075         2444.038137
28                           448.603636       4734.866336         2392.811083
29                           452.895111       4853.895152         2397.608075
30                           479.193051       4948.637024         2490.053565
31                           460.682355       4970.284459         2375.661077
32                           463.416120       4958.144778         2459.132773
33                           484.575658       5085.822591         2388.256857
34                           477.436230       5239.596664         2404.553176
35                           455.588962       5260.229302         2368.844072
36                           416.387858       5199.486165         2336.113530
37                           434.887709       5171.248433         2487.102307
38                           452.828748       4836.756446         2502.234159
39                           452.828748       4577.010985         2458.503330
40                           452.828748       4617.110235         2580.564588
41                           452.828748       4529.377863         2620.021498
42                           452.828748       4409.671770         2733.762409
43                           452.828748       4476.712633         2805.410158
44                           452.828748       4538.004924         2864.938273
45                           452.828748       4620.721826         2945.986636
46                           452.828748       4676.709877         2967.567874
47                           452.828748       4712.518835         2931.829023
48                           452.828748       4801.762530         3258.258351
49                           452.828748       4789.001497         3370.235498
50                           452.828748       4133.134512         3300.450490
51                           452.828748       4495.529265         3309.710671

    Coal Actual  Transportation carbon dioxide emissions Actual  \
0   2311.126560                                     2263.336813
1   2187.743724                                     2352.662168
2   2283.000112                                     2492.989811
3   2443.490583                                     2624.260159
4   2386.105741                                     2556.368151
5   2388.027333                                     2577.130243
6   2563.195745                                     2700.961919
7   2627.566307                                     2805.805592
8   2602.873837                                     2920.220529
9   2843.300211                                     2899.750450
10  2924.836740                                     2789.706724
11  3016.997098                                     2761.261172
12  2894.453933                                     2698.007231
13  3009.112576                                     2707.416975
14  3225.430596                                     2770.797704
15  3326.168963                                     2833.080796
16  3272.427202                                     2932.293175
17  3406.837920                                     3024.922701
18  3584.902972                                     3143.865763
19  3617.355257                                     3165.742537
20  3638.854087                                     3158.617365
21  3610.042113                                     3114.038523
22  3635.494141                                     3153.668515
23  3758.272863                                     3194.926637
24  3770.835057                                     3280.664965
25  3813.294965                                     3351.855474
26  3984.510120                                     3451.104988
27  4067.450536                                     3491.039804
28  4098.322338                                     3564.888343
29  4102.382660                                     3657.169779
30  4293.881862                                     3768.910461
31  4167.281271                                     3711.563437
32  4172.197235                                     3790.961793
33  4257.868684                                     3825.198300
34  4285.010742                                     3934.943640
35  4350.835494                                     3976.275391
36  4278.512602                                     4039.056250
37  4336.251597                                     4044.474542
38  4268.147608                                     3784.660595
39  3756.028591                                     3663.563918
40  3972.695120                                     3691.595412
41  3750.400971                                     3633.718334
42  3315.753311                                     3560.770465
43  3440.059630                                     3614.691326
44  3431.628172                                     3650.893114
45  2968.063701                                     3700.757759
46  2715.282356                                     3776.025765
47  2642.989821                                     3809.483170
48  2531.149755                                     3868.898393
49  2160.215370                                     3879.401066
50  1755.849253                                     3298.672725
51  2017.214715                                     3629.705992

    Residential carbon dioxide emissions Actual  \
0                                    955.538394
1                                    966.514498
2                                    990.067779
3                                    949.582197
4                                    900.987199
5                                    899.900507
6                                    945.132872
7                                    917.072452
8                                    912.628744
9                                    845.760394
10                                   770.299655
11                                   718.852439
12                                   715.432611
13                                   677.145313
14                                   724.429863
15                                   715.998096
16                                   698.703342
17                                   709.064810

In [ ]:
import matplotlib.pyplot as plt

# Plot each group separately
for group_name, group_data in grouped:
    plt.plot(group_data['year'], group_data['value'], label=group_name)

# Add labels and title
plt.xlabel('Year')
plt.ylabel('Value')
plt.title('Line Chart')

# Add legend
plt.legend()

# Show the plot
plt.show()

In [23]:
# Calculate the index to split the DataFrame
split_index = int(len(pivot_df_sorted) * 0.75)

# Split the DataFrame into 75% first rows and 25% last rows
train = pivot_df_sorted.iloc[:split_index]
test = pivot_df_sorted.iloc[split_index:]

# Print the lengths of both splits
print("Length of the first 75%:", len(train))
print("Length of the last 25%:", len(test))

Length of the first 75%: 585
Length of the last 25%: 195